### ISSUE TITLE
Some code blocks are not included in asciidoc

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#102]
Open igchartview-adding-igchartview-uiview.adoc in Livewire.
Scroll down to the full code view.
Only ObjectiveC code is there.  There should also be C#.  It is present in the online help.  It is not present in the AsciiDoc.  I thought this might be from only rendering code snippets that start with "In C#:" but that's present.
Found this also in iggridview-filtering-attributes.adoc.
Submitted bug 212176 in case the one I described in that bug was a content issue with the header.

**Comment by craigshoemaker** [comment]
This is fixed in the latest build.
