### ISSUE TITLE
Online help and .adoc topic do not match

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#105]
Open (CommonControls) resources-sample-bubble-data.adoc.
Compare with the online help:
http://help.infragistics.com/doc/WPF/2015.2/?page=Resources_Sample_Bubble_Data.html
The .adoc file and the online help are completely different.  One is only an .xml file, and the other is a full topic.  The topic names are the same. What am I doing wrong?

**Comment by craigshoemaker** [comment]
This is fixed in the source documents per Martin Trela.
