### ISSUE TITLE
"temp content" appears in the topic

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#106]
Open xamsparkline-interpolating-unknown-values.adoc in Livewire.
Look at the overview header underneath the "in this topic" section.
"temp content" appears.  It should not.
We had discussed this with regards to internal anchor tags.  You can't remove "empty" anchor tags because they are used to show where links inside the topic point.  I think that this is a result of some work you may have done with them.

http://help.infragistics.com/Help/Doc/WPF/2012.1/CLR4.0/html/xamSparkline_Interpolating_Unknown_Values.html

**Comment by craigshoemaker** [comment]
Nothing a little regex tweak can't fix ;)

**Comment by craigshoemaker** [comment]
still an issue per @ig-ealbert
