### ISSUE TITLE
Sentence is cut off after API link

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#110]
Open xamwebmap-display-map-accessdata-using-shapefiles.adoc in Livewire.
Observe step 7.
It should be

```
Create a ShapeFileReader object to read information from the Shapefiles and perform the desired data mappings.
```

It is

```
ShapeFileReader
```

**Comment by craigshoemaker** [comment]
This is fixed by 85224c27e156007de2e216de873747c74252748e as it shares the same problem as #112
