### ISSUE TITLE
First part of the topic is not rendered in Livewire preview

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#111]
Open xampivotgrid-connecting-to-an-oracle-xmla-datasource.adoc in Livewire.
Observe the top of the topic, under the title.
There should be a paragraph before the bulleted list.  It is not rendered.
http://help.infragistics.com/doc/Silverlight/2015.2/?page=xamPivotGrid_Connecting_to_an_Oracle_XMLA_DataSource.html

**Comment by craigshoemaker** [comment]
This one is an edge case. The first paragraph is not wrapped in a paragraph element so it's not processed correctly. I am adding this to the manual fix list.

**Comment by ig-ealbert** [comment]
TFS 219335 - Fixed
