### ISSUE TITLE
no line breaks within table cells

### ISSUE THREAD

**Issue by jVanZwieten** [Infragistics/convertwire#113]
winganttview-resource-strings.adoc
http://help.infragistics.com/doc/WinForms/2015.2/?page=WinGrid_Modify_Suppress_the_Row_Deletion_Message_Box.html

Cells requiring line breaks for paragraphs and lists are just block text.  Check the 6 last rows.
Similar to this issue: https://github.com/Infragistics/convertwire/issues/49
But the fix for that issue only mentioned table titles, dunno if it is applied to cell content.

**Comment by josheela** [comment]
similar issue  : 
docx: wintooltipmanager-api-overview.adoc
onlinelink: http://help.infragistics.com/doc/WinForms/2015.2/?page=WinToolTipManager_API_Overview.html

issue: the key classes UltraToolTipInfo and UntratoolTipManager links should be on different lines in the table.

**Comment by craigshoemaker** [comment]
The issue reported by @jVanZwieten is fixed in the latest build (probably from an earlier commit). The issue reported by @josheela is as expected. Layout tables are broken into plain text on purpose during conversion in order to simplify the generated AsciiDoc.
