### ISSUE TITLE
Period is escaped with backslash?

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#118]
Open wingauge-back-anchor-extent-pane.adoc in Livewire.

2E7ED74F-ECE5-48CC-84FF-C9703E896D9C

Observe the first sentence in the second paragraph.

`from 0 to 100\.`

Why is there a backslash before the period?  It's not there in the .xml file.

**Comment by craigshoemaker** [comment]
The cause of this issue is not obvious. A hack-ish fix would be to use `.replace(/\\\.\ /g, () = > { return '. '; });`, but I'll think on this some more before I go that route.
