### ISSUE TITLE
Hierarchical list is not properly rendered

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#119]
http://help.infragistics.com/doc/Silverlight?page=xamRibbon_xamRibbon_User_Customization_Interface_Ribbon_And_QAT_Customization_Dialog.html

Open xamribbon-xamribbon-user-customization-interface-ribbon-and-qat-customization-dialog.adoc in Livewire.  Observe the section under "in this topic".

In Livewire preview, it all runs together - there is no list.

**Comment by craigshoemaker** [comment]
Looks like a previous commit may have remedied this problem. Here's what I see now:

![image](https://cloud.githubusercontent.com/assets/127797/13060730/4b826eca-d3e8-11e5-8d04-d6d2aab874eb.png)

The Japanese version renders the list correctly as well.
