### ISSUE TITLE
Code is missing from ordered list

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#121]
Open xamtreemap-adding-xamtreemap-using-xaml.adoc in Livewire.
Observe step 3.
Compare with the online help.
http://help.infragistics.com/doc/Silverlight/2015.2/?page=xamTreemap_Adding_xamTreemap_Using_Xaml.html
The code is missing in step 3.  Related to #112 that was fixed.

f80bc6a6-9681-4cd1-9fff-8885df093d75

**Comment by craigshoemaker** [comment]
the topic is fine - the code just didn't show up in the preview pane because the correct build flag wasn't applied
