### ISSUE TITLE
Bottom half of contents are missing

### ISSUE THREAD

**Issue by yoshimis** [Infragistics/convertwire#122]
datachart-axis-title.ja-JP.adoc
About bottom half of contents are missing (Under Axis Title). 

2c429d69-56ef-44e2-ad27-631b71f3843b

**Comment by yoshimis** [comment]
Same issue in datachart-axis-title.adoc.

2c429d69-56ef-44e2-ad27-631b71f3843b

**Comment by craigshoemaker** [comment]
The reason this is happening is because there isn't enough whitespace generated after the `endif` statement. I'll add it to the conversion logic.
