### ISSUE TITLE
“ifdef” is appearing in the preview of adoc.

### ISSUE THREAD

**Issue by yoshimis** [Infragistics/convertwire#128]
“ifdef” is appearing in the preview of following adoc files. *Same for corresponding EN adoc files.

LinearGauge
xamarin-adding-linear-gauge.ja-JP.adoc

RadialGauge
radialgauge.ja-JP.adoc
radialgauge-configuring-needles.ja-JP.adoc
radialgauge-configuring-the-scale.ja-JP.adoc
radialgauge-configuring-tick-marks.ja-JP.adoc
radialgauge-getting-started-with-radialgauge.ja-JP.adoc

**Comment by craigshoemaker** [comment]
closed by a7fa1f4a66dbfbb99335c9a06a66fb1f741da44d
