### ISSUE TITLE
XAML topics: None of the images is displayed.

### ISSUE THREAD

**Issue by gedinakova** [Infragistics/convertwire#132]
1. Load any XAML topic containing images in Livewire, e.g. wpf\topics\xamdatapresenter-change-the-location-of-the-groupbyarea.adoc.
2. Note how the image in step 2 is displayed.

Actual Result: The image is displayed with an icon and a name.

Expected Result: The actual image should be shown. 
Please, refer to the attached screenshots.

![expectedimage](https://cloud.githubusercontent.com/assets/16817847/14525854/333250ae-0248-11e6-9772-4df49e118342.png)
![actualresult](https://cloud.githubusercontent.com/assets/16817847/14525855/33366c34-0248-11e6-8c82-0bea9424d25a.png)

**Comment by ig-ealbert** [comment]
I think this is intentional at this stage.  You're referencing an image that doesn't exist in the directory from which you're opening the .adoc file.  If you copy the images folder into the folder where you have the .adoc files (as a subfolder), it should appear.  @craigshoemaker can verify this.

**Comment by craigshoemaker** [comment]
@ig-ealbert is correct. Livewire supports images just fine, if you want to see them you need to pull them into the directory that is referenced by the image link.
