### ISSUE TITLE
[XAML] Table border and header background are missing

### ISSUE THREAD

**Issue by martotkd1** [Infragistics/convertwire#133]
1.Load for example SL "ig-excel-engine-adding-a-shape-to-an-excel-worksheet.adoc" topic in Livewire
2. Scroll down till "Supported Shapes" section is displayed
Actual result: table border and header background are missing
Expected result: table border and header background should be displayed
Please refer to the attached screenshot
![issue](https://cloud.githubusercontent.com/assets/16817726/14526339/4c79dca0-024b-11e6-96a5-2f5efc794a8d.png)

**Comment by ig-ealbert** [comment]
I think this is expected.  Livewire doesn't reference the Infragistics stylesheets that were previously used in the online help.  It's just doing some default rendering of a table.  @craigshoemaker can confirm this.

**Comment by craigshoemaker** [comment]
@ig-ealbert is correct. This is by design. Thanks, @martotkd1 for noting it though!

**Comment by martotkd1** [comment]
Okay
