### ISSUE TITLE
XAML topics: Numbered lists' indentation is not honored (all levels start at the same indent).

### ISSUE THREAD

**Issue by gedinakova** [Infragistics/convertwire#134]
1. Load wpf\topics\xamdatapresenter-styling-data-errors.adoc in Livewire
2. Scroll to "Follow these Steps" section
3. Note how the list is displayed

Actual Result: The 2 list levels ("1." & "a.") start at the same indent.
Expected Result: The second level should be indented to the right.

**Comment by craigshoemaker** [comment]
closed by 4fede1e200cd82c2f005dbdb6fca30cbcd86ca4c

**Comment by gedinakova** [comment]
Verified
