### ISSUE TITLE
[XAML] All links are converted with '-' instead of '_'

### ISSUE THREAD

**Issue by Teodor-Tenev** [Infragistics/convertwire#135]
**Steps to reproduce:**
1. Open any of the .adoc in LiveWire (e.g. CommonControls > topics > resources-xamgantt-custom-project-view-code-example.adoc)
2. Navigate to the bottom of the page
3. Observe the hyperlink "Code Example Creating View for xamGantt using Custom Classes"
**Actual Result**:
link:xamgantt-code-example-creating-view-for-xamgantt-using-custom-classes.html
**Expected Result**:
The link should be: 
http://www.infragistics.com/help/silverlight/xamGantt_Code_Example_Creating_View_for_xamGantt_using_Custom_Classes.html

**Comment by ig-ealbert** [comment]
This is by design.  Ignite UI help does the same thing.  @craigshoemaker can explain it.

**Comment by craigshoemaker** [comment]
@ig-ealbert is correct. This is by design to better support search engine performance.
