### ISSUE TITLE
Bold italic text is not displayed properly.

### ISSUE THREAD

**Issue by gedinakova** [Infragistics/convertwire#137]
1. Load wpf\topics\xamdiagram-adding-to-a-page.adoc topic in Livewire
2. Scroll to "Overview" section
3. Note the first item in the list

Actual Result: The xamDiagram is only italic and enclosed in asterisks instead of being bold.
![brokenboldformatting](https://cloud.githubusercontent.com/assets/16817847/14526974/90bdd304-024f-11e6-9a67-dff291d10436.png)

Expected Result: xamDiagram should be bold & italic.

**Comment by gedinakova** [comment]
Not fixed! It's currently displayed as follows:
![bolditalicissue](https://cloud.githubusercontent.com/assets/16817847/15928829/f7bfcf3e-2e51-11e6-829b-c110b19d6d74.png)

**Comment by ig-ealbert** [comment]
@gedinakova : This has to be fixed in DocX.

```
<p><span class="ig-bold">1. Adding the</span> <i><span class="ig-bold">xamDiagram</span></i> <span class="ig-bold">control</span></p>
```

I'll fix it now.

**Comment by ig-ealbert** [comment]
Should be fixed in final conversion, as I removed the extra spans, and kept just the bold for the whole step and the italics around the control name.
