### ISSUE TITLE
[SL] Bold and new line issues in "Adding a Shape to an Excel Worksheet" topic

### ISSUE THREAD

**Issue by martotkd1** [Infragistics/convertwire#138]
1.Load SL "ig-excel-engine-adding-a-shape-to-an-excel-worksheet.adoc" topic in Livewire
2. Scroll down till "Steps" section is displayed
 Actual result: first sentence is not bold. Second sentence is not on a new line. \* is displayed
 Expected result: first sentence should be bold. Second sentence should be on a new line. \* should not be displayed.
 Please refer to the attached screenshot
![issue](https://cloud.githubusercontent.com/assets/16817726/14527118/6db477fe-0250-11e6-8852-ba014c6c199f.png)

**Comment by craigshoemaker** [comment]
The bold issue is now remedied, but there will still be no line break as AsciiDoc uses whitespace to delineate sections in lists.

**Comment by martotkd1** [comment]
Verified the text is bold now.
