### ISSUE TITLE
[WPF] Doc X code snippets are not parsed/colorized correctly

### ISSUE THREAD

**Issue by sboykova** [Infragistics/convertwire#139]
Example: wpf topics - xamdiagram-configuring-the-diagram-items-content-visualization.adoc

![screenshot2](https://cloud.githubusercontent.com/assets/11226391/14527710/645cfaa6-0254-11e6-8c0a-6cedfbe37963.png)

**Comment by ig-ealbert** [comment]
Duplicate with #146.  Also I think it's expected as the colorizing is not done in the HTML preview.  It will be done in the build. @craigshoemaker can confirm.

**Comment by craigshoemaker** [comment]
@ig-ealbert is correct about code colorization. I will look at the parsing issue for now.
