### ISSUE TITLE
[XAML] Notes are not styled and the tag is duplicated

### ISSUE THREAD

**Issue by Teodor-Tenev** [Infragistics/convertwire#140]
**Steps to reproduce:**
1. Open any of the .adoc which contains Notes in LiveWire (e.g. "wpf\topics\xamdatapresenter-about-record-filtering.adoc")

**Actual Result**:
Notes are not styled and there is a duplication in the word "Note":
![clip2net_160414145415](https://cloud.githubusercontent.com/assets/660170/14527174/c4d3023a-0250-11e6-8de9-0b50ba505a4d.png)

**Expected Result**:
Notes should be styled, and there shouldn't be such a duplication of the word as it should also start on a new line.
![clip2net_160414145451](https://cloud.githubusercontent.com/assets/660170/14527189/dba16ff6-0250-11e6-8584-17aa5004c630.png)

**Comment by craigshoemaker** [comment]
The styling of notes in Livewire is to have the gray bar at the side. 

I will look into the replicated labels though.

**Comment by craigshoemaker** [comment]
This is a content issue that needs to be fixed in the topic. The extra Note label is in a paragraph before the DIV with the `ig-note` class applied to it - the note label needs to be deleted and it will convert as expected.

I will add to the manual fix list.

GUID: {E0F0E3B3-595B-4428-840F-FE008022A52B}

**Comment by ig-ealbert** [comment]
@craigshoemaker : @phoenixcat noted that this happens in "any" topic that has notes.  I could fix the one occurrence, but that may not be what is reported.  Can you suggest a way to fix this on a product scale?

**Comment by craigshoemaker** [comment]
I'll look into this some more

**Comment by craigshoemaker** [comment]
I figured out a way to handle this in an automated fashion.
