### ISSUE TITLE
[SL] When unorder list items are links, they are not parsed correctly

### ISSUE THREAD

**Issue by sboykova** [Infragistics/convertwire#141]
Example: Silverlight topics - ig-imaging-exporting-a-bitmapsource-to-image.adoc

![screenshot1](https://cloud.githubusercontent.com/assets/11226391/14527547/724c3862-0253-11e6-845d-83b35fdd55ad.png)

**Comment by craigshoemaker** [comment]
Can not reproduce. I was working on the list code in other areas. Perhaps something I did in another commit fixed this issue.

Here's what I see now:

![image](https://cloud.githubusercontent.com/assets/127797/14649475/037e266c-061c-11e6-80c8-96129e4a2e4a.png)
