### ISSUE TITLE
[SL] Topic tags are added in the topic content

### ISSUE THREAD

**Issue by sboykova** [Infragistics/convertwire#142]
Example - sl-copy-cell-format.adoc

![screenshot4](https://cloud.githubusercontent.com/assets/11226391/14530595/53836fae-0262-11e6-9475-621916d6075a.png)

**Comment by ig-ealbert** [comment]
Duplicate with #148.

**Comment by sboykova** [comment]
Duplicate with https://github.com/Infragistics/convertwire/issues/148
