### ISSUE TITLE
Tags "[source,XAML]" shown in the content before the snippets in "Adding xamDiagram to a Page" topic.

### ISSUE THREAD

**Issue by gedinakova** [Infragistics/convertwire#143]
1. Load xamdiagram-adding-to-a-page.adoc in Livewire
2. Scroll to the second "Steps" section
3. Check the text before the XAML snippets

Actual Result: The text is "In XAML:[source,XAML]".
Expected Result: The [source,XAML] part should not be shown.

**Comment by craigshoemaker** [comment]
closed by c4a14de793452ae9b107529118b4427b6964d7bd

**Comment by gedinakova** [comment]
Verified
