### ISSUE TITLE
[XAML] {Warning} tag should not be visible as content

### ISSUE THREAD

**Issue by Teodor-Tenev** [Infragistics/convertwire#145]
**Steps to reproduce:**
1. Open wpf/topics/xamribbon-display-custom-key-tips.adoc in LiveWire 
2. Observe
**Actual Result**:
{Warning} tag is visible as content
**Expected Result**:
{Warning} tag should not be visible as content

**Comment by ig-ealbert** [comment]
Duplicate of #84.
https://github.com/Infragistics/convertwire/issues/84
