### ISSUE TITLE
[XAML] Code snippets are not colorized

### ISSUE THREAD

**Issue by Teodor-Tenev** [Infragistics/convertwire#146]
**Steps to reproduce:**
1. Open any of the .adoc with code snippet in LiveWire (e.g. CommonControls > topics > resources-xamgantt-custom-project-view-code-example.adoc)
2. Observe
**Actual Result**:
Code snippets are not colorized
**Expected Result**:
Code snippets should be colorized

**Comment by ig-ealbert** [comment]
Duplicate with #139.  Also I think it's expected as the colorizing is not done in the HTML preview.  It will be done in the build.

**Comment by craigshoemaker** [comment]
@ig-ealbert is correct. I should have stated the styling expectations better at the outset :smile:
