### ISSUE TITLE
[XAML] "Related Topics" are missing styling

### ISSUE THREAD

**Issue by Teodor-Tenev** [Infragistics/convertwire#147]
**Steps to reproduce:**
1. Open  wpf> topics > xampropertygrid-user-interactions.adoc
2. Scroll down to the bottom of the doc.

**Actual Result**:
"Related Topics" are missing styling
![image](https://cloud.githubusercontent.com/assets/660170/14531900/c7c74caa-0267-11e6-8781-3e3207e0649b.png)

**Expected Result**:
"Related Topics" should be styled.

**Comment by ig-ealbert** [comment]
Again, I think this is expected because all Livewire does is to render the HTML.  It doesn't apply any styles.  @craigshoemaker can confirm this.

**Comment by craigshoemaker** [comment]
@phoenixcat @ig-ealbert that is correct

Sometimes the markup that comes out of DocumentX is a big mangled so we don't end up with a similar result as to what we see published. For instance sometimes people just bold Related Topics while others (correctly) make it a header. So this is one of those where it's a known issue that the conversion won't be 100% perfect.
