### ISSUE TITLE
[XAML] Extra content is added at the bottom of the page

### ISSUE THREAD

**Issue by Teodor-Tenev** [Infragistics/convertwire#148]
**Steps to reproduce:**
1. Open CommonControls > topics > xamgrid-copypastehelpermethods.adoc in LiveWire
2. Scroll down to the bottom of the topic

**Actual Result**:
_Data Presentation, Exporting, Grids, How Do I, Tips and Tricks_ are displayed at the bottom of the topic

**Expected Result**:
There should not be such words there

**Comment by ig-ealbert** [comment]
Duplicate with #142.

**Comment by Teodor-Tenev** [comment]
Verified!
