### ISSUE TITLE
[XAML] Long code snippets are wrapped. Scrollbar should be visible instead.

### ISSUE THREAD

**Issue by Teodor-Tenev** [Infragistics/convertwire#150]
**Steps to reproduce:**
1. Open  CommonControls > topics > resources-sampledatautil.adoc in LiveWire
2. Observe

**Actual Result**:
 Long code snippets are wrapped.
**Expected Result**:
Scrollbar should be visible instead.

**Comment by craigshoemaker** [comment]
This is a feature request for Livewire. [I have created an issue for it here](https://github.com/Infragistics/livewire/issues/66).
