### ISSUE TITLE
[WF] - API link was not converted properly and missing

### ISSUE THREAD

**Issue by jVanZwieten** [Infragistics/convertwire#153]
//reproduction
wingroupbox-place-an-image-next-to-a-caption.adoc
http://help.infragistics.com/doc/WinForms?page=WinGroupBox_Place_an_Image_Next_to_a_Caption.html

//result
![missingheaderappearancelink](https://cloud.githubusercontent.com/assets/16783024/14536241/64b4d6aa-023f-11e6-82c8-680fa8f446ad.PNG)
"locate in the property grid the <missing> property"

//expected
"locate in the property grid the HeaderAppearance (as an API link) property"
![headerappearanceexpected](https://cloud.githubusercontent.com/assets/16783024/14536302/aaaebae0-023f-11e6-8e35-011b23045583.PNG)

**Comment by jVanZwieten** [comment]
More instances of this in case more evidence is needed:
wintoolbarsmanager-controlcontainer-about-the-controlcontainer-tool.adoc
winformattedtexteditor-the-winformattedtexteditor-smart-tag.adoc
wintab-disable-and-hide-tabs-in-wintab.adoc
wintab-display-a-close-button-on-a-tab.adoc

**Comment by jVanZwieten** [comment]
Sorry, I got confused.

**Comment by jVanZwieten** [comment]
While many topics have API links missing, this one interestingly had the API link properly there:
wingrid-displaying-vertical-borders-in-columns.adoc

**Comment by craigshoemaker** [comment]
This is a build flagged link. If you press the `win-forms-clr2` button at the bottom of the windows, does it appear?

**Comment by jVanZwieten** [comment]
It's magic !!

Yes, that's working on every document posted here.  It seems this is working as intended.
