### ISSUE TITLE
[WF] code snippet in table

### ISSUE THREAD

**Issue by jVanZwieten** [Infragistics/convertwire#154]
//reproduce
touch-enabled-schedule-controls.adoc
http://help.infragistics.com/doc/WinForms?page=Touch_enabled_Schedule_Controls.html

//result
![codesnippetnestedintableresult](https://cloud.githubusercontent.com/assets/16783024/14543768/cb109f64-0263-11e6-9105-dca992bc151b.PNG)

code snippets appear as text instead of in a box

//expected
![codesnippetnestedintableexpected](https://cloud.githubusercontent.com/assets/16783024/14543783/e14299ae-0263-11e6-81b3-91c4f99eba3c.PNG)

//note
found these annoying "+" at the end of the code snippet lines, once removed the snippet showed as expected.

**Comment by craigshoemaker** [comment]
the `+` is used to concatenate content in an AsciiDoc table. Code in tables have been a sticking point in the past. I will look further into this.

**Comment by craigshoemaker** [comment]
closed by c4a14de793452ae9b107529118b4427b6964d7bd
