### ISSUE TITLE
[WF] tables have equal spacing

### ISSUE THREAD

**Issue by jVanZwieten** [Infragistics/convertwire#156]
//reproduce
windropdown-smart-tag.adoc
http://help.staging.infragistics.local/Doc/WinForms/2016.1/CLR4.0/?page=WinDropDown_Smart_Tag.html

//result
![tableequalspacing](https://cloud.githubusercontent.com/assets/16783024/14545271/c207b292-026b-11e6-9aa2-f168711178e6.PNG)
converted table gives equal spacing to columns

//expected
![tableequalspacingexpected](https://cloud.githubusercontent.com/assets/16783024/14545281/ced035c6-026b-11e6-9882-c6b1fab37eb8.PNG)
original table is very wide and gives most spacing to the description, resulting in mostly single or a few line rows; looks kind of weird in converted

**Comment by ig-ealbert** [comment]
We had problems with Document X's decisions on column widths.  Sometimes it would make columns widths stupidly small, so only 1 character would fit on each line.  You can see this in the Japanese help and we got complaints.  It was horrible (insert grumpy cat here).  I'm rather happy with how column widths are handled in the asciidoc preview.  @craigshoemaker can confirm but I think we don't control this.  Not sure exactly what he's using for the preview renderer but it would be related to that, right?

**Comment by craigshoemaker** [comment]
There are ways to have [AsciiDoc enforce column widths](http://www.methods.co.nz/asciidoc/newtables.html), but this is not currently supported in the conversion. 

I'll take a look at how much effort is required to add it, but if I don't add it and we find a topic that really needs it we can fix it manually.

**Comment by craigshoemaker** [comment]
I'm closing this and marking it as `wontfix` even though it's not technically a bug in the conversion process. In general the default column width spacing is sufficient for most topics. Adding this functionality may create tables that don't look right after conversion.

If there is still an issue for individual topics we can fix them on a case-by-case basis.
