### ISSUE TITLE
[WF] "Note:" replaced with "{warning}" and the note is found at the bottom

### ISSUE THREAD

**Issue by jVanZwieten** [Infragistics/convertwire#157]
//reproduce
wintoolbarsmanager-ribbon-groups.adoc
http://help.infragistics.com/doc/WinForms?page=WinToolbarsManager_Ribbon_Groups.html

//result
![warning](https://cloud.githubusercontent.com/assets/16783024/14546031/65c130ee-0270-11e6-8a5d-77c9bbc6f914.PNG)
we find "{Warning}" where there used to be a "**Note:**
![note at bottom](https://cloud.githubusercontent.com/assets/16783024/14546044/7a268872-0270-11e6-9144-24652185c23d.PNG)
and the actual note is at the bottom of the page

//expected
![expected](https://cloud.githubusercontent.com/assets/16783024/14546057/87b08358-0270-11e6-9426-3fcf6be99f47.PNG)

**Comment by ig-ealbert** [comment]
Duplicate with #84 and #145.  If the actual note is at the bottom of the page, then that might be a bug.  @craigshoemaker can verify.

**Comment by craigshoemaker** [comment]
Yes, this is the same issue as #84 and #145

**Comment by jVanZwieten** [comment]
At this time the note has dissapeared.  The warning is still there, but it sounds from #84 that this is expected behavior. However, since the note dissapearing seams to be a separate issue, I'll open this bug back up so you can make that determination.

**Comment by ig-ealbert** [comment]
@craigshoemaker: "{Warning}" is a variable that holds the entire note, right?  When variables are implemented (or shown in Tripwire?  Not sure of the status of this feature), the entire note paragraph should be inserted at the top of the file.  Is that correct?
