### ISSUE TITLE
[WF] odd occurance of a topic referencing a topic

### ISSUE THREAD

**Issue by jVanZwieten** [Infragistics/convertwire#158]
//reproduce
wingrid-autosuggest-highlight-appearance.adoc
wincomboeditor-autosuggest-highlight-appearance.adoc
http://help.staging.infragistics.local/Doc/WinForms/2016.1/CLR4.0/?page=WinGrid_AutoSuggest_Highlight_Appearance.html
http://help.staging.infragistics.local/Doc/WinForms/2016.1/CLR4.0/?page=WinComboEditor_AutoSuggest_Highlight_Appearance.html

//result
I guess the original WinGrid topic just points to the WinComboEditor topic and they share the same topic.  Problem is the converted WinGrid topic first has the title, then includes the other .adoc, causing a duplicated title:
![duplicatedtitle](https://cloud.githubusercontent.com/assets/16783024/14546218/12170e9e-0272-11e6-83db-33bb62aa4b4a.PNG)

**Comment by craigshoemaker** [comment]
I'll look closer at this, but we will probably have to adjust the content in DocumentX to accommodate the conversion for this one.

**Comment by jVanZwieten** [comment]
While we're doing it on a case by case basis, wouldn't it just be easier to make the manual modifications directly to the adoc ?

**Comment by craigshoemaker** [comment]
We just need to have the title removed from 1dd0e107-91d0-45c2-b015-e41c2ecc0c19 in DocumentX
