### ISSUE TITLE
[WF] header hierarchy lost

### ISSUE THREAD

**Issue by jVanZwieten** [Infragistics/convertwire#159]
//reproduce
wincomboeditor-autosuggest-highlight-appearance.adoc
http://help.staging.infragistics.local/Doc/WinForms/2016.1/CLR4.0/?page=WinGrid_AutoSuggest_Highlight_Appearance.html

//result
in cases where we are undoing the table, the row header is converted into an H3.  This is often the same as the label above it, which causes 2 labels of H3 on top of each other, which breaks up the hierarchy scheme:
![h3](https://cloud.githubusercontent.com/assets/16783024/14546489/aa5d01b2-0273-11e6-9534-be464cbe88da.PNG)

//expected
it would be better to have the label above the row label be H2 to show hierarchy (this ss just shows a clear info hierarchy):
![h3 expected](https://cloud.githubusercontent.com/assets/16783024/14546503/c69af456-0273-11e6-8d90-612702656fe6.PNG)

**Comment by craigshoemaker** [comment]
closed by 2f633d50c3c979a2ef9a636989a9c16f73bded07
