### ISSUE TITLE
API Overview of Data Chart topic incorrect bullets

### ISSUE THREAD

**Issue by pamelabrasil** [Infragistics/convertwire#16]
datachart-api-overview.adoc

The bullets are not displayed correctly on this page. 
The bullet points are not listed on new lines

**Comment by craigshoemaker** [comment]
Tables are hard to get right in an automated conversion. This one will have to be manually fixed by using the [AsciiDoc guide on tables](http://www.methods.co.nz/asciidoc/newtables.html).

I am noting this file name and we need to find a good place to document files that will need manual fixes.
