### ISSUE TITLE
[WPF] Heading 4 looks like regular text

### ISSUE THREAD

**Issue by rmkrmk** [Infragistics/convertwire#161]
I am not sure if this is intentional, but all headings 4 (defined with four equals sign) are looking like the rest of the text. See screenshot:

![image](https://cloud.githubusercontent.com/assets/11978058/14553735/e13f1a30-02f0-11e6-801b-3867274c8e7b.png)

**Comment by craigshoemaker** [comment]
This is just an issue in the stylesheet that is being used in Livewire. We can adjust these.

**Comment by rmkrmk** [comment]
Verified
