### ISSUE TITLE
[WPF] Some list items are merged

### ISSUE THREAD

**Issue by rmkrmk** [Infragistics/convertwire#162]
Open WPF topics / xamDiagram-configuration-overview.adoc
Scroll down to "Start and end"
The second list item ("Absolute") is merged with the first one ("Relative").
See screenshot:

![image](https://cloud.githubusercontent.com/assets/11978058/14553868/c5e4a1be-02f1-11e6-9d63-33db4a230b0f.png)

**Comment by craigshoemaker** [comment]
This isn't an issue with the conversion, but rather the original markup. There is a stray `<BR>` in the middle of the text that needs to be removed before conversion.

So this: 

`respectively.<BR>This approach requires`

needs to be changed to this:

`respectively. This approach requires`

Adding to the manual fix list.

**Comment by ig-ealbert** [comment]
TFS 219329.  Fixed.

**Comment by rmkrmk** [comment]
Verified
