### ISSUE TITLE
[WPF] Some custom CSS classes are not honored

### ISSUE THREAD

**Issue by rmkrmk** [Infragistics/convertwire#163]
The following CSS classes are not always honored
- custom list levels "ig-level-1", "ig-level-2", (no indentation, no bullets)
- "ig-bold"
- standard HTML tag <u> (for underline)

**Comment by craigshoemaker** [comment]
@rmkrmk can you please provide a file name to reproduce with?

**Comment by rmkrmk** [comment]
Issue 1 ("ig-level-x"):
wpf.zip / xamdatagrid-external-filtering.adoc
(go to "External Filtering – Code Example" / "Prerequisites")

Issue 2 ("ig-level-x" and "ig-bold"):
wpf.zip / xamdatagrid-sorting-overview.adoc
(the "In This Topic" section)

Issue 3 (I was not able to find again the issue with the underline, but I found one with bold &lt;b&gt;):
wpf.zip / xambusyindicator-applying-custom-animation.adoc
(in step 3 "Create a CustomBusyAnimation object...")

**Comment by rmkrmk** [comment]
Verified
