### ISSUE TITLE
[XAML] List item missing

### ISSUE THREAD

**Issue by rmkrmk** [Infragistics/convertwire#165]
Open commoncontrols.zip / xamgrid-create-a-custom-filter.adoc
Look in the "Follow these Steps" section.
The first list item's number is missing (see screenshot):
![image](https://cloud.githubusercontent.com/assets/11978058/14554582/9285375c-02f6-11e6-868f-83adb99ae12f.png)
(not sure, what exactly is missing in the markup)

**Comment by craigshoemaker** [comment]
The problem with this item is that the markup in the source document has a `<p>` inside the `<li>` so during conversion the text in the paragraph is rendered on a new line breaking the ordered list item.

The paragraph tag needs to be removed from the source document. This:

```
<LI><P>Create your own custom class that inherits from <A href...
```

needs to be changed to this...

```
<LI>Create your own custom class that inherits from <A href...
```

and the ending `</P>` needs to be removed as well.

**Comment by ig-ealbert** [comment]
@craigshoemaker : Do we know if this is an isolated issue or a widespread one?  I can fix it in TFS if it's isolated.

**Comment by craigshoemaker** [comment]
@ig-ealbert as far as I know this is a one-off instance

**Comment by ig-ealbert** [comment]
I can't seem to search for this pattern in the XML files using Notepad++.
Logged TFS 219333 and fixed it.

**Comment by rmkrmk** [comment]
Verified
