### ISSUE TITLE
[SL] Topics are not rendered correctly in "What’s New in 2014 Volume 2" topic

### ISSUE THREAD

**Issue by tachojelev** [Infragistics/convertwire#167]
**Steps to reproduce:**
1. Open wpf.zip /whats-new-in-2014-volume-2.adoc
2. Navigate to "Infragistics Excel Engine" section

**Actual Result:**
All topics from including "Infragistics Excel Engine" until the bottom of the page are not rendered correctly.
(Refer to the attached image)
**Expected Result:**
All topic from including "Infragistics Excel Engine" until the bottom of the page should be rendered correctly.

![rendering](https://cloud.githubusercontent.com/assets/12784974/14560055/c9453c3c-0315-11e6-84bf-98bace9ab99f.png)

**Comment by craigshoemaker** [comment]
The offending issue for this topic must have been corrected with a previous commit as I do not see any issue with the topic at this time.

**Comment by tachojelev** [comment]
Verified.
