### ISSUE TITLE
"User Selection Interactions and Usability (xamComboEditor)" topic: A misplaced "+" character breaks one of the images.

### ISSUE THREAD

**Issue by gedinakova** [Infragistics/convertwire#168]
1. Load commoncontrols\topics\xamcomboeditor-selection-overview.adoc in Livewire
2. Scroll to the bottom
3. Note how the Yes.png is displayed in the last cell of "Configurable?" column

Actual Result: A "+" character placed after the "[]" prevents the image from showing. 
"|image::images/Yes.png[] +"
Expected Result: The "+" should not be there and the Yes.png should be shown.

**Comment by craigshoemaker** [comment]
This is fixed from an earlier commit - likely this one 088442c4e9d26efbf038c7cd323386eb2d994661

**Comment by gedinakova** [comment]
Verified
