### ISSUE TITLE
Chart Axes Topic

### ISSUE THREAD

**Issue by pamelabrasil** [Infragistics/convertwire#17]
datachart-axes.adoc

Missing content - under Required Backgroud, and the In this topic section is missing
The build flag on Label Angle and LabelExtent appears with ifdef info in the design view
Under Axis Types - NumericXAxis appears with project variables 
There is no visible way in the design view to know what build flags are set

**Comment by craigshoemaker** [comment]
for the missing content this is closed by ea18ac3e6bf6d513f6e1ebeef2f7aa887e2fca38

regarding the other issue, Livewire does not yet support visual affordances for build flags defined in the topic - it's coming though!
