### ISSUE TITLE
"Binding Shapefiles" topic: XAML & C# code snippets are broken.

### ISSUE THREAD

**Issue by gedinakova** [Infragistics/convertwire#170]
1. Load commoncontrols\topics\xamwebmap-display-map-accessdata-using-shapefiles.adoc in Livewire
2. Press the "wpf" button at the bottom to show the wpf version of the topic
3. Scroll down to step 7
4. Note the XAML & C# code snippet 

Actual Result: The snippets are broken in 2 parts and are not formatted properly. Each of the 2 parts is surrounded by an empty (or containing "[source]" only) code snippet rectangle.

Expected Result: The whole code snippets should be placed in the code snippet rectangles.
![brokencodesnippets](https://cloud.githubusercontent.com/assets/16817847/14561008/20b804c6-031c-11e6-8e4f-6f9c66a40cf2.png)

**Comment by jVanZwieten** [comment]
Also has some broken up snippet, likely due o being within/after a ul:
//reproduce
known-issues-windesktopalert.adoc  (ta-hp)
http://help.infragistics.com/doc/TestAutomationHPWinForms/?page=Known_Issues_WinDesktopAlert.html

//result
![brokensnippet](https://cloud.githubusercontent.com/assets/16783024/14691366/de285064-071e-11e6-8dae-0226b254885d.PNG)
What should be 1 snippet is broken into 2 with the last 4 lines outside the snippet.

//expected
![brokensnippetexpected](https://cloud.githubusercontent.com/assets/16783024/14691386/f43168d2-071e-11e6-8586-979eac732eb4.PNG)
admittedly, there seems to be something messed up here as well.
