### ISSUE TITLE
[SL] The subsection bullets in the "Overview" section of the "Creating a Simple Text Editor Using the DocumentContentHost container" topic have an incorrect indentation

### ISSUE THREAD

**Issue by tachojelev** [Infragistics/convertwire#174]
**Steps to reproduce:**
1. Open wpf.zip /xamdockmanager-simpletexteditor-with-documentcontenthost.adoc
2. Navigate to the "Overview" section

**Actual Result:**
The subsection bullets for "5. Handling events" bullet do not have a proper indentation.

**Expected Result:**
The subsection bullets for "5. Handling events" bullet should have a proper indentation.

![identation](https://cloud.githubusercontent.com/assets/12784974/14561905/4478c6b0-0322-11e6-8f82-45cbaba8114a.png)

**Comment by craigshoemaker** [comment]
This issue was resolved by a previous commit.

**Comment by tachojelev** [comment]
Verified.
