### ISSUE TITLE
Missing numeration in Steps section

### ISSUE THREAD

**Issue by zenikolov** [Infragistics/convertwire#176]
1. Load xamdatagrid-cellvaluepesenterstyleselector-reevaluated.adoc in Livewire
   2.Scroll to the Steps section

Actual Result: 
Missing numeration 
![image](https://cloud.githubusercontent.com/assets/9294621/14562341/b8182a5a-0324-11e6-83e2-dabfa5e1aa07.png)

Expected Result: 

Numeration should be visible

**Comment by zenikolov** [comment]
I was able to reproduce the same issue after the fix. 

Actual Result: 
![image](https://cloud.githubusercontent.com/assets/9294621/15962079/57dbead2-2f11-11e6-93fd-ed4357af23bf.png)

Expected Result: 
![image](https://cloud.githubusercontent.com/assets/9294621/15962071/445bfce0-2f11-11e6-851d-59c94d05d226.png)

**Comment by ig-ealbert** [comment]
@zenikolov : I get a different result.  Could you please verify that you're opening the latest version of the converted topics, and that you have the latest version of Livewire?
![image](https://cloud.githubusercontent.com/assets/8162597/15967951/d984ef62-2ef7-11e6-957e-51eb99831506.png)

**Comment by zenikolov** [comment]
I double checked it and I get the correct result, so it is fixed and verified.
