### ISSUE TITLE
"Related Topics" caption is not on a new line in "Data Slicer (xamPivotGrid)" topic.

### ISSUE THREAD

**Issue by gedinakova** [Infragistics/convertwire#177]
1. Load commoncontrols\topics\xampivotgrid-dataslicer.adoc in Livewire
2. Scroll to the bottom
3. Note the "Related Topics" section

Actual Result: "Related Topics" is shown as part of the figure's description.
Expected Result: "Related Topics" should be on a new line.

**Comment by craigshoemaker** [comment]
closed by 561fe223a4f5b16169d8a923f5b0a5dce4116a78

**Comment by gedinakova** [comment]
Verified
