### ISSUE TITLE
"..." is shown as "-" in the converted code snippets in "Programmatically Add Summaries" topic.

### ISSUE THREAD

**Issue by gedinakova** [Infragistics/convertwire#178]
1. Load commoncontrols\topics\xamgrid-programmatically-add-summaries.adoc in Livewire
2. Note the code snippets

Actual Result: The "..." is shown as "-".
Expected Result: The "..." should be preserved.

**Comment by craigshoemaker** [comment]
This is no longer an issue. It must have been fixed via an earlier commit.

**Comment by gedinakova** [comment]
Verified
