### ISSUE TITLE
Missing hyperlink for Custom Resources in Related Content section

### ISSUE THREAD

**Issue by zenikolov** [Infragistics/convertwire#179]
1. Load xamgantt-creating-custom-resources-for-xamgantt.adoc in Livewire
2. Scroll to the Related Content section 

Actual Result:  'Custom Resources' hyperlink is missing 
![pasted image at 2016_04_14 01_58 pm](https://cloud.githubusercontent.com/assets/9294621/14562600/45f9f76c-0326-11e6-885e-78c0554d5b1a.png)
Expected Result:  'Custom Resources' hyperlink should be visible

**Comment by craigshoemaker** [comment]
This issue is fixed via a previous commit. Likely this one 9d3f73156eaca1cc90cd181d1345ec345fb60e33

**Comment by zenikolov** [comment]
Verified
