### ISSUE TITLE
Configuring Axis Crossing

### ISSUE THREAD

**Issue by pamelabrasil** [Infragistics/convertwire#18]
datachart-axis-crossing.adoc

Code snippets do not appear in design view
Within the C# / VB code snippets there are also build flags for code specific to Winforms / XAML, these build flags do not appear.

**Comment by craigshoemaker** [comment]
I'm unclear as to the problem here. I tried the topic and if you put a build flag at the top the corresponding code block appears. Can you elaborate, please?

**Comment by ig-ealbert** [comment]
I just checked how the topic is parsed in the asciidoc and compared it to the XML file in TFS (9d54f719).  It is parsed correctly.
The code snippets not appearing in design is what Craig explained - they aren't shown unless you manually type out the build flag at the top.
Within the C# and VB code snippets, there are no build flags for code specific to WinForms or XAML, or at least there aren't in the serialized XML file.

**Comment by craigshoemaker** [comment]
closing per Liz's comments above.
