### ISSUE TITLE
Missing image for cell merging feature

### ISSUE THREAD

**Issue by zenikolov** [Infragistics/convertwire#180]
1. Load xamgrid-merged-cells.adoc in Livewire

2.Observe Figure 1 

Actual Result: 
Figure 1 does not exist

![image](https://cloud.githubusercontent.com/assets/9294621/14562798/7cc4a14c-0327-11e6-98f8-b211520066b1.png)

Expected Result: 

Figure 1 should be visible

![image](https://cloud.githubusercontent.com/assets/9294621/14562811/8e9afeca-0327-11e6-88db-b4d856d6d5e8.png)

Notes: You can observe the same about 'Figure 2' , 'Figure 3'  ,  'Figure 5' and  'Figure 6'

**Comment by craigshoemaker** [comment]
The images are build-flagged. If you apply a build flag to the topic in Livewire (buttons in the bottom right corner), then you see the images appear.

**Comment by zenikolov** [comment]
Verified
