### ISSUE TITLE
[SL] In the "Adding Panes and Content to xamDockManager" topic, the hyperlinks under "Overview" section are not on individual rows, the table under "Introduction" section is incorrectly formatted and an enumeration is missing in the "Steps" section for "Adding a Calendar" topic

### ISSUE THREAD

**Issue by tachojelev** [Infragistics/convertwire#181]
**0:** Open wpf.zip /xamdockmanager-adding-panes-and-content-to-xamdockmanager.adoc

**1**) The hyperlinks under "Overview" section are not on individual rows
**Steps to reproduce:**
Navigate to the "Overview" section.
**Actual Result:**
The hyperlinks under "Overview" section are not on individual rows.
**Expected Result:**
The hyperlinks under "Overview" section should be on individual rows.
## ![newrows](https://cloud.githubusercontent.com/assets/12784974/14563087/c0fa0fae-0328-11e6-9013-2c0907b871c7.png)

**2**) The table under "Introduction" section is incorrectly formatted
**Steps to reproduce:**
Navigate to the "Introduction" section.
**Actual Result:**
The table under "Introduction" section is incorrectly formatted.
**Expected Result:**
The table under "Introduction" section should be correctly formatted.
## ![wrongformat](https://cloud.githubusercontent.com/assets/12784974/14563148/1cd32112-0329-11e6-8334-e2d6a7bf14fa.png)

**3**) An enumeration is missing in the "Steps" section for "Adding a Calendar" topic
**Steps to reproduce:**
Navigate to the steps section of the "Example: Adding a Calendar" topic.
**Actual Result:**
Digits from the enumeration are missing.
**Expected Result:**
Digits from the enumeration should not be missing.
![enum](https://cloud.githubusercontent.com/assets/12784974/14563285/c5dee8fe-0329-11e6-9cb5-b49a7db202e3.png)

**Comment by craigshoemaker** [comment]
I'll look into the list issue, but the nested tables are note supported by the conversion process. This topic is flagged in the nested tables report for manual processing after final conversion.

**Comment by craigshoemaker** [comment]
The un-ordered list items were fixed in a previous commit. The ordered list items are fixed via 3d776667508fee31e4dbeffd3956e9f9cc64feeb
