### ISSUE TITLE
[SL] Unrelated and inappropriate word references at the end of the "Related Topic" section in the "Copy Cell Format" topic

### ISSUE THREAD

**Issue by tachojelev** [Infragistics/convertwire#183]
**Steps to reproduce:**
1. Open wpf.zip /sl-copy-cell-format.adoc
2. Navigate to the "Related Topics" section

**Actual Result:**
There are unrelated and inappropriate word references after the "Format a Cell" hyperlink.

**Expected Result:**
There should not be unrelated and inappropriate word references after the "Format a Cell" hyperlink.

![otherstuff](https://cloud.githubusercontent.com/assets/12784974/14563757/32e9a7d4-032c-11e6-8727-eee59486847d.png)

**Comment by craigshoemaker** [comment]
duplicate of #148

**Comment by craigshoemaker** [comment]
closed by 7ba862fc379de2bbd6e35da55deffa82d8e3005d

**Comment by tachojelev** [comment]
Verified.
