### ISSUE TITLE
piechart selection and explosion Related Topics should be part of topic tree

### ISSUE THREAD

**Issue by IGvaleries** [Infragistics/convertwire#187]
open piechart-selection-and-explosion.adhoc

the beginning of the topic looks as follows 
![converted](https://cloud.githubusercontent.com/assets/18487709/14569838/1776056e-030f-11e6-822d-717c2e394044.PNG)

it should appear as:
![old](https://cloud.githubusercontent.com/assets/18487709/14569864/4378309c-030f-11e6-9b4b-02637009d9a8.PNG)

**Comment by craigshoemaker** [comment]
Closed by 3c16f26c48ceee50b2cafbb6b2bae1f1641b3710
