### ISSUE TITLE
piechart - binding OLAP data table in required background is incorrect

### ISSUE THREAD

**Issue by IGvaleries** [Infragistics/convertwire#188]
open piechart-binding-olap-data.adoc
required background appears as 
![converted](https://cloud.githubusercontent.com/assets/18487709/14570366/e0d816a2-0311-11e6-955b-072ba5b90ec3.PNG)

should be similar to:
![new](https://cloud.githubusercontent.com/assets/18487709/14570472/665b6392-0312-11e6-8596-6b65236118a7.PNG)

**Comment by craigshoemaker** [comment]
This has a nested table in it and is not supported by conversion. This topic will bubble up in the tables report for manual processing.
