### ISSUE TITLE
datachart - configuring default style table is incorrect

### ISSUE THREAD

**Issue by ig-robstoffers** [Infragistics/convertwire#189]
1.) open datachart-new-default-style.adoc
2.) scroll down to "Configuring the default style"

The Livewire table looks like this:
![config-default-style-livewire](https://cloud.githubusercontent.com/assets/18489991/14572793/e9c3bea8-031e-11e6-9cd5-39d41d0fd02f.png)

The table is displayed incorrectly compared to the table in the official docs:
http://help.infragistics.com/Help/Doc/WPF/2015.2/CLR4.0/html/DataChart_New_Default_Style.html

**Comment by craigshoemaker** [comment]
This is a complex table with merged columns/rows and is not supported by the conversion. This will bubble up in the tables report for manual processing.
