### ISSUE TITLE
datachart-axis-label-adoc

### ISSUE THREAD

**Issue by pamelabrasil** [Infragistics/convertwire#19]
The values in the Property Name column is not formatted properly in the design view. 
For example:
pick:[xam_xf_ex="LabelSettings.FontFamily"] pick:[xamarin.winforms.android="LabelFontFamily"]

**Comment by craigshoemaker** [comment]
What is the file name you are looking at here?

In general the `pick:` syntax is for in-line build flags and is not supported by Livewire to resolve final build flag value. That is next on the list though.

**Comment by pamelabrasil** [comment]
the name of the file is in the title.

**Comment by craigshoemaker** [comment]
That's what I thought, but it doesn't map to any real files. I think you either meant *-format, *-templates or *-settings :wink:

**Comment by ig-ealbert** [comment]
This looks like #23 that I had submitted and is now closed based on Craig's explanation.

**Comment by craigshoemaker** [comment]
Closing per Liz's comment above.
