### ISSUE TITLE
datachart - default style doc lists sample link twice

### ISSUE THREAD

**Issue by ig-robstoffers** [Infragistics/convertwire#190]
1.) Open datachart-new-default-style.adoc
2.) Scroll to bottom "Samples" section
3.) Category Series is displayed twice

![default-style-samples](https://cloud.githubusercontent.com/assets/18489991/14573168/61bc3c3a-0321-11e6-84b1-5322a0aed8c7.png)

**Comment by craigshoemaker** [comment]
This seems to be more an issue in Livewire rather than the conversion. I'll open up a new issue over there.
