### ISSUE TITLE
datachart - polar scatter series VB, C#, and XF XAML code snippets not showing

### ISSUE THREAD

**Issue by IGvaleries** [Infragistics/convertwire#191]
file: datachart-polar-scatter-series.adoc

code snippets are missing for visual basic and C# on all platforms except Android and XAML code snippets are also missing for Xamarin Forms

**Comment by craigshoemaker** [comment]
They are there - they just don't show up unless you apply the `android-ex` build flag in Livewire.

**Comment by pamelabrasil** [comment]
Nested build flags are causing code snippets to be duplicated many times

**Comment by ig-ealbert** [comment]
I don't think this is the build flags causing the problem.  It's more likely the nested `<CODE>` blocks.
Ex.

```
&lt;SPAN class=hs-buildflag-markup style="hs-build-flags: XAM_XF_EX,ANDROID,XAMARIN"&gt;series.ItemsSource = polarDataSample&lt;/SPAN&gt;&lt;/CODE&gt;&lt;BR&gt;&lt;CODE class=code&gt;&lt;SPAN class=hs-buildflag-markup style="hs-build-flags: WINFORMS"&gt;series.DataSource = polarDataSample&lt;/SPAN&gt;
```

**Comment by pamelabrasil** [comment]
removed the extra code tags in DocX

**Comment by craigshoemaker** [comment]
@pamelabrasil @ig-ealbert since the extra `CODE` elements are removed, should this issue be closed?

**Comment by ig-ealbert** [comment]
@craigshoemaker - Can you confirm that it's fixed?  If so, yes, it should be closed.

**Comment by HUSSAR-mtrela** [comment]
@ig-ealbert @craigshoemaker 
this looks like wrong build flags in docx:
style="hs-build-flags: XAM_XF_EX,ANDROID,XAMARIN"
which means we are trying to build flag content for all XAML platforms except XF and then build flag XF anyway!!! 
Logic ;)

**Comment by ig-ealbert** [comment]
@HUSSAR-mtrela, Is there a simpler build flag we could use for everything except WinForms?

@craigshoemaker, Did you get a chance to test if this is fixed by removing the `<CODE>` elements?

**Comment by HUSSAR-mtrela** [comment]
@ig-ealbert no, there are no simpler build flag we could use for everything except WinForms. we decided to go away from using *_EX build flags since they increase complexity of our docs. Why kind of content would you need to build flag for everything except WinForms?

**Comment by ig-ealbert** [comment]
@HUSSAR-mtrela : The code in DataChart for the ItemsSource is different in Windows Forms than it is in XAML.
http://help.infragistics.com/doc/winforms/2016.1/?page=DataChart_Creating_Chart_In_Code_Behind_WinForms.html
http://help.infragistics.com/doc/wpf/2016.1/?page=DataChart_Creating_Chart_In_Code_Behind_XAML.html

**Comment by HUSSAR-mtrela** [comment]
We will not have code blocks with nested build flags so any API differences will be separated in code blocks that are build flagged for appropriate product.

**Comment by ig-ealbert** [comment]
I'm still confused.  How do you suggest that this be fixed in DocX? "this looks like wrong build flags in docx"  What can I do to help resolve this issue, if the argument is that the topic needs to be fixed in DocX?

**Comment by HUSSAR-mtrela** [comment]
@ig-ealbert  I will fix this topic in docX by replacing:
"XAM_XF_EX,ANDROID,XAMARIN"
with
"WPF,UWP,ANDROID,XAMARIN"
note that UWP is missing in some cross-platform projects so I will add it.

**Comment by ig-ealbert** [comment]
@HUSSAR-mtrela Won't that exclude the code from the Windows Forms topics?

**Comment by HUSSAR-mtrela** [comment]
@ig-ealbert yes that's the whole point besides XAM_XF_EX does not apply to WF anyway.
series.ItemsSource <== "WPF,UWP,ANDROID,XAMARIN"
series.DataSource <== "WINFORMS"
WF series has DataSource  property and series on rest of platforms have ItemsSource property
I fixed this issue in EN/JP locals so please someone verify it in the next conversion pass. Also, there was a bug in 5e4aa82c-8645-490e-b0d0-dd733c4bec20 topic that had duplicated build flags so I fixed it.

**Comment by craigshoemaker** [comment]
@ig-ealbert @HUSSAR-mtrela let me know if I need to get a later version than what I got yesterday before I do the datachart conversion

**Comment by HUSSAR-mtrela** [comment]
@craigshoemaker yes you need to get latest version because I made these fixes today.
