### ISSUE TITLE
datachart - dimensional data (OLAP Data): text begins with *

### ISSUE THREAD

**Issue by IGvaleries** [Infragistics/convertwire#192]
file: datachart-customizing-series-when-used-with-multi-dimensional-data-(olap-data)-(xamdatachart).adoc

in Overview section there is a star before the text for step 3:
3.*Replacing the default series using a series-creating event

**Comment by craigshoemaker** [comment]
Closed by an earlier commit

**Comment by pamelabrasil** [comment]
fixed in DocX - extra span tags
