### ISSUE TITLE
datachart legend topic duplicate value in types of legends table

### ISSUE THREAD

**Issue by IGvaleries** [Infragistics/convertwire#194]
file: datachart-legends.adoc

for android, xaml-xf-ex, and xamarin Basic Legend is duplicated in types of legends 
![converted](https://cloud.githubusercontent.com/assets/18487709/14611125/b6e077f0-055e-11e6-81bf-b0abac88e38d.PNG)
table:

**Comment by craigshoemaker** [comment]
Can not reproduce. Perhaps this is fixed in another build and may be related to #190
