### ISSUE TITLE
datachart legend topic contains + before table properties

### ISSUE THREAD

**Issue by IGvaleries** [Infragistics/convertwire#195]
file: datachart-legends.adoc
in type of legends table item legend and scale legend appear with + in front
![converted](https://cloud.githubusercontent.com/assets/18487709/14613284/b2a034fe-0569-11e6-8076-31ba9919527c.PNG)

**Comment by craigshoemaker** [comment]
This was resolved via a previous commit

**Comment by pamelabrasil** [comment]
Item legend is not bulleted

**Comment by ig-ealbert** [comment]
The issue that @pamelabrasil points out may be a duplicate of #257.
