### ISSUE TITLE
datachart - series error bars iuncorrect bulleting

### ISSUE THREAD

**Issue by IGvaleries** [Infragistics/convertwire#196]
file datachart-series-error-bars.adoc

introduction, requirements and supported type of series should not be bulleted / indented:
![converted](https://cloud.githubusercontent.com/assets/18487709/14614131/aa9f6906-056d-11e6-8318-bb0b8729fd7c.PNG)

**Comment by ig-ealbert** [comment]
Actually the other top level items _should_ be bulleted.
http://help.staging.infragistics.local/Doc/WPF/2016.1/CLR4.0/?page=DataChart_Series_Error_Bars.html

**Comment by craigshoemaker** [comment]
This was resolved in a previous commit.

**Comment by pamelabrasil** [comment]
Funny issue happening with the Related topics links, probably because of the div tag in DocX, I removed it.
