### ISSUE TITLE
datchart - using multiple axes C# and VB code is not being displayed

### ISSUE THREAD

**Issue by IGvaleries** [Infragistics/convertwire#197]
file: datachart-multiple-axes.adoc

In android-ex view headers for in C# and In VisualBasic are displayed but the code is not. The C# / VB code is also not displayed under any other tag views.

from converted file:
![converted](https://cloud.githubusercontent.com/assets/18487709/14614414/14c97b22-056f-11e6-9fd0-a298edfa9dfd.PNG)

**Comment by craigshoemaker** [comment]
This is the same issue as #203. We'll update Livewire to remedy this.
