### ISSUE TITLE
datachart - using multiple axes XAML source code displays [source] tag

### ISSUE THREAD

**Issue by IGvaleries** [Infragistics/convertwire#198]
file: datachart-multiple-axes.adoc

XAML source code for xamarin and xaml-xf-ex appears incorrect with [source] tag breaking code which should be continuous. For example:
![converted](https://cloud.githubusercontent.com/assets/18487709/14614522/8fcb69e8-056f-11e6-933a-6fc1cf4cf740.PNG)

**Comment by craigshoemaker** [comment]
This was resolved in a previous commit.

**Comment by pamelabrasil** [comment]
there are some

**Comment by pamelabrasil** [comment]
random code tags in the code snippet which I believe caused some broken XAML. I removed those code tags
