### ISSUE TITLE
bulletgraph - adding: android view contains XAML

### ISSUE THREAD

**Issue by IGvaleries** [Infragistics/convertwire#201]
file: bulletgraph-adding.adoc

In Xaml section should not be included in Android, source.js should be omitted and extra ---- around namespaces should be removed:
![converted](https://cloud.githubusercontent.com/assets/18487709/14619329/0dc5bc26-0585-11e6-855b-e921e535ae7a.PNG)

**Comment by IGvaleries** [comment]
for other platforms the In XAML namespace is repeated

**Comment by craigshoemaker** [comment]
This is a nested table and is not supported during conversion. This will bubble up through the nested table report and will need some manual processing.
