### ISSUE TITLE
bulletgraph - adding: namespace references include langauge descriptions in []

### ISSUE THREAD

**Issue by IGvaleries** [Infragistics/convertwire#205]
file bulletgraph-adding.adoc
[source,csharp] , [source,vb] should be removed along with extra ----

ex winforms:
![converted](https://cloud.githubusercontent.com/assets/18487709/14619922/01baffec-0588-11e6-9918-4a829281d99c.PNG)

ex xaml: 
![converted](https://cloud.githubusercontent.com/assets/18487709/14619946/1e747a0a-0588-11e6-9492-ce4d5f360b10.PNG)

**Comment by IGvaleries** [comment]
a similar issue can be found in bulletgraph-configuring-the-title-subtitle
![converted](https://cloud.githubusercontent.com/assets/18487709/14654770/42ada8b8-064d-11e6-994f-9e54c806d80f.PNG)
.adoc:

**Comment by craigshoemaker** [comment]
Fixed by c4a14de793452ae9b107529118b4427b6964d7bd
