### ISSUE TITLE
bulletgraph - configuring the orientation and direction: related Content should not be bulleted ender example

### ISSUE THREAD

**Issue by IGvaleries** [Infragistics/convertwire#206]
file: bulletgraph-configuring-the-orientation-and-direction.adoc

Related topic should appear in top level of tree:
converted view:
![converted](https://cloud.githubusercontent.com/assets/18487709/14620270/ca499832-0589-11e6-9f30-089371c1c9cb.PNG)

previous view:
![old](https://cloud.githubusercontent.com/assets/18487709/14620293/ddb70f6c-0589-11e6-8a22-e96c0021fa8c.PNG)

**Comment by ig-ealbert** [comment]
This seems related to #196.
http://help.staging.infragistics.local/Doc/WPF/2016.1/CLR4.0/?page=BulletGraph_Configuring_the_Orientation_and_Direction.html

**Comment by craigshoemaker** [comment]
this is resolved by 6ff624459a4069a78aacf9f48a345351fc02681b
