### ISSUE TITLE
android samples contains extra text with ==

### ISSUE THREAD

**Issue by IGvaleries** [Infragistics/convertwire#207]
file: android-android-samples.adoc
should display name of samples browser not:
[Infragistics {PlatformName} Samples Browser]] == Samples Browser

converted:
![converted](https://cloud.githubusercontent.com/assets/18487709/14620589/79b5bc6e-058b-11e6-8302-c4e08613bd7c.PNG)

previous:
![old](https://cloud.githubusercontent.com/assets/18487709/14620607/9390b3fa-058b-11e6-9e52-11531311cdb0.PNG)

**Comment by craigshoemaker** [comment]
I am closing this issue even though the actual symptom will only by partially resolved with the associated commit. I have updated the logic to create in-document link targets (815afb843ed09aa6eef62713a559a2eca4cb10c5), but ultimately Livewire needs to be updated to support build variables. Once build variables are supported then the `{PlatformName}` token will resolve to the final value and then the topic will render correctly in the preview pane.
