### ISSUE TITLE
bulletgraph - configuring the performance bar - WPF - sample name duplicated

### ISSUE THREAD

**Issue by IGvaleries** [Infragistics/convertwire#209]
file: bulletgraph-configuring-the-performance-bar.adoc:
scroll to bottom of page - performance bar settings is duplicated:
![converted](https://cloud.githubusercontent.com/assets/18487709/14649500/593e82b8-0635-11e6-854d-776838b61a7a.PNG)

**Comment by IGvaleries** [comment]
this can also be found in WPF for bulletgraph-configuring-the-title-subtitle.adoc:
![converted](https://cloud.githubusercontent.com/assets/18487709/14654814/72fc4b1e-064d-11e6-8c12-4c29952b7fc8.PNG)
and bulletgraph-configuring-the-tootips.adoc

**Comment by ig-ealbert** [comment]
In the HTML these are build-flagged for SL and WPF.  If the build-flags on sample links are not kept in the .adoc file, that's a widespread bug.

```
&lt;P class=ig-topic-link style="hs-build-flags: SL"&gt;&lt;A class=ig-topic-link href="%%SamplesURL%%/bullet-graph/#/basic-configuration" target=_blank&gt;Basic Configuration&lt;/A&gt;&lt;/P&gt;
&lt;P class=ig-topic-link style="hs-build-flags: WPF"&gt;&lt;A class=ig-topic-link href="%%SamplesURL%%/bullet-graph/basic-configuration" target=_blank&gt;Basic Configuration&lt;/A&gt;&lt;/P&gt;
```
