### ISSUE TITLE
Bullet points do not render properly in tables

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#21]
Bullet points do not render properly in tables.  They show up as `*` instead of as the bullet point.
Example topics:
datachart-chart-navigation.ja-JP.adoc
datachart-navigating-chart-using-code.ja-JP.adoc
datachart-series-error-bars.ja-JP.adoc
datachart-new-default-style.ja-JP.adoc

**Comment by craigshoemaker** [comment]
closed by f38ab41e4a05c3de3c3599141f4278ef3dceb852
