### ISSUE TITLE
bulletgraph configuring the scale extra text [[_Configuring_the_Scale’s]]

### ISSUE THREAD

**Issue by IGvaleries** [Infragistics/convertwire#210]
file: bulletgraph-configuring-the-scale.adoc
![converted](https://cloud.githubusercontent.com/assets/18487709/14649888/147856d4-0637-11e6-9d9c-de6d450520ab.PNG)

**Comment by ig-ealbert** [comment]
Awesome `<h2>` block in the HTML.  This is a content bug.  Convertwire is handling it properly.  If you log a TFS bug, I can fix it.

```
<h2><a name="_Configuring_the_Scale’s"></a><a name="_Ref362957272"></a><a name="_Ref362967447"></a><a name="_Ref361864088"></a><a name="_Ref357787115"></a><a name="_Ref358209468"></a>Configuring the Scale’s Range</h2>
```

**Comment by craigshoemaker** [comment]
I labeled this to fix in DocX

**Comment by ig-ealbert** [comment]
Bug 219301 in TFS.  Will fix it there.
This seems to be a widespread issue on the header elements in this topic.  There are so many anchor tags for each of them!

**Comment by ig-ealbert** [comment]
Fixed in TFS.
