### ISSUE TITLE
xamarin known issues and limitations - format issues

### ISSUE THREAD

**Issue by IGvaleries** [Infragistics/convertwire#212]
file: xamarin-known-issues-and-limitations.adoc
1) iOS issues not cleanly bulleted under Platform Specific Issues:

converted:
![converted](https://cloud.githubusercontent.com/assets/18487709/14686202/aafa354a-0705-11e6-9b27-ceddfe76f6c5.PNG)

previous:
![old](https://cloud.githubusercontent.com/assets/18487709/14686211/b38c9702-0705-11e6-9a25-26d8051f6547.PNG)

2) In CTP Features and Controls missing line break before Data Chart Feature 

converted:
![converted](https://cloud.githubusercontent.com/assets/18487709/14686316/24adacdc-0706-11e6-9705-85c8deec608c.PNG)

previous:
![old](https://cloud.githubusercontent.com/assets/18487709/14686318/2bc0b0e6-0706-11e6-816c-ef861c0ee1f1.PNG)

**Comment by craigshoemaker** [comment]
closed by 3d776667508fee31e4dbeffd3956e9f9cc64feeb
