### ISSUE TITLE
xamarin whats new in 2015 volume 2 - header with wrong styling

### ISSUE THREAD

**Issue by IGvaleries** [Infragistics/convertwire#213]
file: whats-new-whats-new-in-2015-volume-2.adoc

style of topic "Support for Windows phone" is incorrect:

converted:
![converted](https://cloud.githubusercontent.com/assets/18487709/14687075/a5b63850-0709-11e6-8e34-873261d04dbd.PNG)

previous:
![old](https://cloud.githubusercontent.com/assets/18487709/14687078/aa310702-0709-11e6-9ffd-da9fd0b4d86e.PNG)

**Comment by ig-ealbert** [comment]
I'm not sure, but this might be caused by an `<a>` tag inside the `<h1>` tag.

```
<H1>Support for Windows Phone Removed<A id=Support_for_Windows_Phone_Removed name=Support_for_Windows_Phone_Removed></A></H1>
```

If that's the case, I can fix it.
