### ISSUE TITLE
datachart - Chart Axes

### ISSUE THREAD

**Issue by mddifilippo89** [Infragistics/convertwire#216]
1. Related content links missing where applicable.

**Comment by ig-ealbert** [comment]
There is a stray ifdef::sl,wpf right under the Related Content section, which makes everything not appear unless the sl or wpf build flag is chosen in Livewire.  This build flag doesn't seem to exist in the source HTML file.  I expect it would work if that was not there.

**Comment by mddifilippo89** [comment]
related content links are now properly build flagged.
