### ISSUE TITLE
[ta-hp] missing space after star for bolded intermediate titles

### ISSUE THREAD

**Issue by jVanZwieten** [Infragistics/convertwire#219]
//reproduce
http://help.infragistics.com/doc/TestAutomationHPWinForms/?page=Known_Issues_General_Known_Issues.html
known-issues-general-known-issues.adoc

//result
![headersmissingstar](https://cloud.githubusercontent.com/assets/16783024/14691120/7401e5fc-071d-11e6-820c-d89db044a93c.PNG)

//expected
![headermissingstarexpected](https://cloud.githubusercontent.com/assets/16783024/14691128/7bf83cc0-071d-11e6-8ce4-2ed38c9217f1.PNG)

**Comment by jVanZwieten** [comment]
May be related, missing a line bread before a star:
//reproduce
known-issues-restyled-run-time-dialogs.adoc
http://help.infragistics.com/doc/TestAutomationHPWinForms/?page=Known_Issues_Restyled_Run_Time_Dialogs.html

//result
![spacebeforestar](https://cloud.githubusercontent.com/assets/16783024/14691206/fbc98f80-071d-11e6-9635-4505c069086d.PNG)

//expected
![spacebeforestarexpected](https://cloud.githubusercontent.com/assets/16783024/14691209/fdede9fa-071d-11e6-9fac-67bb350910a8.PNG)

**Comment by craigshoemaker** [comment]
The first issue was resolved in a previous commit. The second one is just because the HTML in the source document isn't correct. It is set as a `DIV` with bolded text, so it's being converted correctly. This is a one-off; the source just needs to updated to switch those headings to `H3` elements.

**Comment by ig-ealbert** [comment]
Bug 219323 in TFS.  Fixed.
