### ISSUE TITLE
Internal anchors are not converted properly to HTML

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#221]
Convert any topic in R+ Desktop help to HTML.
Internal anchors like `[#GridView]` are not converted as blank links.
Actual result:
`<h2 id="GridView">Grid View</h2>`
I think it is supposed to be like this:
`<h2><a id="GridView" name="GridView"></a>GridView</h2>`
Not sure if both the id and name are needed.

**Comment by ig-ealbert** [comment]
This seems to be working using the ID on an element.
Tested using 2 WPF topics (new for 17.1) and clicking on internal links.  They work, even though the result is like the "Actual result" listed above.
This does seem to initially convert back to asciidoc correctly.
If we could confirm that this behavior is correct and works, then this issue could be closed.

**Comment by craigshoemaker** [comment]
I am going to go ahead and close this as the `id` is the only attribute relevant to internal anchor locations. The "actual" result is semantically correct and more precise.
