### ISSUE TITLE
Encoding is changed to UTF8 without BOM

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#224]
Convert any R+ Desktop topic to HTML and back to AsciiDoc.
In HTML, the encoding is correct (UTF-8 with BOM).
In AsciiDoc, the encoding is changed to remove the BOM, which results in garbled text.
Ex.
http://tfs.infragistics.local:8080/tfs/Engineering/EnterpriseMobility/_git/reportplus-desktop-docs-ja/commit/4ad351b4ca77e0225360872021ada87ec039a13b

**Comment by craigshoemaker** [comment]
this is now resolved
