### ISSUE TITLE
`{nbsp} +` gets converted to HTML as a block

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#225]
Convert the home-page.adoc file from R+ Desktop help to HTML.
In AsciiDoc:
`{nbsp} +`
In HTML:
`<p>�<br></p>`
You can see this here:
http://tfs.infragistics.local:8080/tfs/Engineering/EnterpriseMobility/_git/reportplus-desktop-docs-ja/commit/18414cf8fff01061f1608c84f049661c111b1822#path=%2Ftopics%2Fhome-page.adoc&_a=compare

**Comment by craigshoemaker** [comment]
Closing as determined it was an encoding issue.
