### ISSUE TITLE
[ta-hp] missing line break in Topics links

### ISSUE THREAD

**Issue by jVanZwieten** [Infragistics/convertwire#227]
//reproduce
test-automation-for-infragistics-controls.adoc
http://help.infragistics.com/doc/TestAutomationHPWinForms/?page=Test_Automation_for_Infragistics_Controls.html

//result/expected
![topicslinks](https://cloud.githubusercontent.com/assets/16783024/14692922/af896842-0728-11e6-95a3-bf8a6deea7a7.PNG)
topics links are both on the same line; should be a line break

**Comment by craigshoemaker** [comment]
Closed by 9e436e827eee5ed9d3c95113423251d8e4c95e7b
