### ISSUE TITLE
[ta-hp] line break before table links missing

### ISSUE THREAD

**Issue by jVanZwieten** [Infragistics/convertwire#228]
//reproduce
whats-new.adoc
http://help.infragistics.com/doc/TestAutomationHPWinForms/?page=Whats_New.html

//result
![linebreakbeforelink](https://cloud.githubusercontent.com/assets/16783024/14693065/d59fbb3e-0729-11e6-9709-5af2b613a91a.PNG)
links are either missing (in the case of "What's New in 2015 Volume 2") or in the preceeding paragraph ("Revision History")

//expected
![linebreakbeforelinkexpected](https://cloud.githubusercontent.com/assets/16783024/14693084/f0f6acc6-0729-11e6-801f-21a419a0c762.PNG)

**Comment by jVanZwieten** [comment]
There's also a lack of line break after the title here.  Let me know if you think this is a seperate issue:
whats-new-in-2008-volume-3.adoc
http://help.infragistics.com/doc/TestAutomationHPWinForms/?page=Whats_New_in_2008_Volume_3.html

**Comment by jVanZwieten** [comment]
This one is missing a line break before a header in a UL.  Again, I'll include it here and let me know if you think it's a seperate issue:
rft-whats-new-in-2007-volume-3.adoc
http://help.infragistics.com/doc/TestAutomationIBMWinForms/2015.2?page=RFT_Whats_New_in_2007_Volume_3.html

**Comment by craigshoemaker** [comment]
Each of these items are fixed. The first is closed by 9e436e827eee5ed9d3c95113423251d8e4c95e7b, the second is closed by 5b834c4f2ab97a50a35b10fca385ef970d503ec5 and the last one is closed by ec8331ddaa217cd02206e2b0b6d24bf9561e511e
