### ISSUE TITLE
[ta-hp] 1 too many "=" in a header in a table

### ISSUE THREAD

**Issue by jVanZwieten** [Infragistics/convertwire#229]
//reproduce
whats-new-2015-volume-2.adoc
http://help.infragistics.com/doc/TestAutomationHPWinForms/?page=Whats_New_2015_Volume_2.html

//result
![toomanyequals](https://cloud.githubusercontent.com/assets/16783024/14693210/e1afba18-072a-11e6-8907-ee36bd906fba.PNG)
Note the 5 "="

//expected
![toomanyequalsexpected](https://cloud.githubusercontent.com/assets/16783024/14693215/efd7da26-072a-11e6-9a8a-ba2f89a1c709.PNG)

**Comment by ig-ealbert** [comment]
This might be related to #220.

**Comment by jVanZwieten** [comment]
Appears here too: rft-whats-new-in-2013-volume-2.adoc
http://help.infragistics.com/doc/TestAutomationIBMWinForms/2015.2?page=RFT_Whats_New_in_2013_Volume_2.html

**Comment by jVanZwieten** [comment]
And here: rft-whats-new-in-2014-volume-1.adoc
http://help.infragistics.com/doc/TestAutomationIBMWinForms/2015.2?page=RFT_Whats_New_in_2014_Volume_1.html

**Comment by craigshoemaker** [comment]
closed by 2f633d50c3c979a2ef9a636989a9c16f73bded07
