### ISSUE TITLE
[ta-hp] ramdomize missing UL bullet

### ISSUE THREAD

**Issue by jVanZwieten** [Infragistics/convertwire#230]
//reproduce
whats-new-in-2010-volume-3.adoc
http://help.infragistics.com/doc/TestAutomationHPWinForms/?page=Whats_New_in_2010_Volume_3.html

//result
![missingul](https://cloud.githubusercontent.com/assets/16783024/14693390/6d010ada-072c-11e6-8e17-64be945a39bd.PNG)
"PerformToolAction" is in paragraph

//expected
![missingulexpected](https://cloud.githubusercontent.com/assets/16783024/14693399/7de4008c-072c-11e6-9572-bb3e9fef1a83.PNG)
should be in a bullet

**Comment by jVanZwieten** [comment]
I may have been unclear on the issue seen here.
The "PerformToolAction" bolded item should be the first item of the UL (RibbonApplicationMenuCloseUp being the 2nd). PeformToolAction is still not a UL item, causeing the + seen before "Now the single" instead of adding that para into the UL item:
![ullack](https://cloud.githubusercontent.com/assets/16783024/16048555/8d77817e-3222-11e6-8323-d85808ee1e22.PNG)

**Comment by ig-ealbert** [comment]
@craigshoemaker, @jVanZwieten - Looks like the `<p>` tags for the PerformToolAction first paragraph would have to be removed in the source file.  This is assuming that the second list item "RibbonApplicationMenuCloseUp" is rendered correctly.  The difference below is the direct child `<p>` after `<li>`.  This would fixed in Document X.  Please confirm.

```
<ul>
    <li>
        <p><b>PerformToolAction</b> - Performs a specified tool action based on the supplied tool.&nbsp;Previously there were 73 different hard coded actions and each action represented the GeneralActionName (Click, DropDown, Set, and Select), the ToolRegion (Menu, Toolbar, QAT, ApplicationMenu, Ribbon, MiniToolbar, tabItem, NavToolbar and NavMenu) and the ActionQualifier (Font, Combo, ColorPicker, TextBox and MaskedEdit).</p>

        <p>Now the single PerformToolAction replaces the 73 different recorded actions. You can just use the PerformToolAction with the required parameters. For the tool region and tool action parameters pass in the QTPToolRegion and QTPToolAction enumeration values. The old actions will still replay for existing scripts.</p>
    </li>
</ul>

<ul>
    <li>
        <b>RibbonApplicationMenuCloseUp</b> - Closes the ribbon’s application menu.

        <p>The existing RibbonApplicationMenuDropDown action is available for both standard application menus as well as application 2010 menus.</p>
    </li>
</ul>
```
