### ISSUE TITLE
[ta-rft] OL in a table converted to "[start=<i>]"

### ISSUE THREAD

**Issue by jVanZwieten** [Infragistics/convertwire#232]
//reproduce
wincarousel-using-wincarousel-control-proxy.adoc
http://help.infragistics.com/doc/TestAutomationIBMWinForms/2015.2?page=WinCarousel_Using_WinCarousel_Control_Proxy.html

//result
![olintable](https://cloud.githubusercontent.com/assets/16783024/14715391/a3546138-07b6-11e6-9999-ce385b4cf391.PNG)

//expected
![olintableexpected](https://cloud.githubusercontent.com/assets/16783024/14715396/aa768d1a-07b6-11e6-9392-de1c7ebdf82a.PNG)

**Comment by craigshoemaker** [comment]
this was fixed in a previous commit
