### ISSUE TITLE
datachart-creating-chart-in-ms-blend-xaml - missing links to api - bug

### ISSUE THREAD

**Issue by ghost** [Infragistics/convertwire#235]
[First table]
*Should be:
/link:{DataChartLink}.Axis{ApiProp}Label.html[Name]
/string
/xAxis
/Sets the identifying name of the axis element

*Should be:
/link:{DataChartLink}.Axis{ApiProp}Label.html[ItemSource]
/string
/{Binding}
/Sets the ItemsSource property for the axis

[Second table] 
Should be:
/link:{DataChartLink}.Axis{ApiProp}Title.html[Name]
/string
/yAxis
/Sets the identifying name of the axis element  

*[This note is immediately following second table]
Note
Numeric YAxis automatically calculates MinimumValue <missing API link> and MaximumValue <missing API link> based on range of data bound to the Series objects and you don’t have sets these properties.

*[Third table]
/====
/Property Name|Property Type|Property Value|Notes

/Name<missing API link>
/string
/AreaSeries

**Comment by ig-ealbert** [comment]
@ckearse - Do you see the same actual result here?
http://help.infragistics.com/doc/wpf/2016.1/?page=DataChart_Creating_Chart_In_MS_Blend_XAML.html
If so, please log a bug in TFS and provide the expected links.
It looks like Convertwire is handling this properly.

**Comment by craigshoemaker** [comment]
@ig-ealbert is correct the contents of this topic are being converted correctly. I have added the `fix-in-DocX` label so the original contents can be fixed before the final conversion
