### ISSUE TITLE
radialgauge-configuring-needles - AndroidEx code snippets are not build flagged properly - bug

### ISSUE THREAD

**Issue by ghost** [Infragistics/convertwire#236]
Build flags for Android-Ex and WinForms overlap, preventing either from being properly displayed within the topic.

![image](https://cloud.githubusercontent.com/assets/14225200/14727618/e4f33e40-07fa-11e6-831c-f3c2b650639c.png)

ifdef::android-ex[]

_In C#:_
## ifdef::win-forms[]

var radialGauge = new {RadialGaugeName}();
radialGauge.Value = 60;
radialGauge. pick:[win-forms="Scale"] EndExtent = 0.5;
radialGauge.NeedleShape = RadialGaugeNeedleShape.Rectangle;
radialGauge.NeedlePivotShape = RadialGaugePivotShape.CircleWithHole;

---

endif::win-forms[]

endif::android-ex[]

ifdef::android-ex[]

_In Visual Basic:_
## ifdef::win-forms[]

 Dim radialGauge As {RadialGaugeName} = New {RadialGaugeName}

radialGauge.Value = 60

radialGauge. pick:[win-forms="Scale"] EndExtent = 0.5

radialGauge.NeedleShape = RadialGaugeNeedleShape.Rectangle

radialGauge.NeedlePivotShape = RadialGaugePivotShape.CircleWithHole

---

endif::win-forms[]

endif::android-ex[]

**Comment by craigshoemaker** [comment]
The topic is converted correctly, this will be fixed as Livewire is updated to better handle build flags
