### ISSUE TITLE
radialgauge-configuring-the-scale - code snippets not build flagged properly for AndroidEx - bug

### ISSUE THREAD

**Issue by ghost** [Infragistics/convertwire#237]
Code snippets headers appear for Android-Ex, but the code snippets are not displayed.

![image](https://cloud.githubusercontent.com/assets/14225200/14727896/9db33dd4-07fd-11e6-8767-3c655217c9b4.png)

**Comment by ig-ealbert** [comment]
This is a duplicate of #236.

**Comment by craigshoemaker** [comment]
The topic is converted correctly, this will be fixed as Livewire is updated to better handle build flags
