### ISSUE TITLE
radialgauge-getting-started-with-radialgauge - numbered step for overview section does not start on a new line - bug

### ISSUE THREAD

**Issue by ghost** [Infragistics/convertwire#238]
Step#1 needs to be moved to a new line

![image](https://cloud.githubusercontent.com/assets/14225200/14727991/c5d1ed3c-07fe-11e6-9eb5-c79e86c9b5d2.png)

**Comment by craigshoemaker** [comment]
The issue with this topic is the that bolded text for the number 1 item is not in a block level element. Notice how it's just in a `b` tag:

```
<P>Following is a conceptual overview of the process:</P><B>1. Adding the %%ControlsName%% control to %%PlatformName%% applications</B> 
<P><B>2. Verifying the results</B></P>
```

The bolded text just needs to be wrapped in a paragraph tag.

**Comment by ig-ealbert** [comment]
Logged as TFS 219615 and fixed.
