### ISSUE TITLE
android-adding-linear-gauge - Overview step#1 needs to be moved to new line - bug

### ISSUE THREAD

**Issue by ghost** [Infragistics/convertwire#239]
Step#1 of the overview section should start on a new line.

![image](https://cloud.githubusercontent.com/assets/14225200/14728133/3b8cc974-0800-11e6-8fa3-2a8685bf5d06.png)

**Comment by ig-ealbert** [comment]
This is a duplicate of #238.

**Comment by craigshoemaker** [comment]
Closed as duplicate

**Comment by ig-ealbert** [comment]
Logged TFS 219617 and fixed.
