### ISSUE TITLE
Related topics header should be displayed

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#24]
"Related Topics" header is not displayed, but is instead build-flagged for Android only.  This should not be the case.
http://help.jp.infragistics.com/doc/WPF/2015.2/CLR4.0/?page=DataChart_Navigating_Chart_Using_Code.html
datachart-navigating-chart-using-code.ja-JP.adoc

**Comment by craigshoemaker** [comment]
This needs to be fixed in the source file. Adding to the manual fix list.

**Comment by ig-ealbert** [comment]
@craigshoemaker: Can you explain why this needs to be fixed in the source file?  There is not an Android build-flag around the "Related Topics" header.
Also, this is an issue I logged in an earlier conversion so let me know if you need me to test it again.

```
&lt;DIV class=ig-block-title style="hs-build-flags: SL,WPF,WINRT,WINFORMS"&gt;
&lt;H2&gt;&lt;A id=RelatedContent name=RelatedContent&gt;&lt;/A&gt;Related Content&lt;/H2&gt;&lt;/DIV&gt;
```

**Comment by ig-ealbert** [comment]
@craigshoemaker : See previous comment.  Also, it seems to be fixed or at least it is in the English.  The same escaped markup is used in Japanese, even though I can't verify the conversion because only the English topics are converted in the latest batch.
