### ISSUE TITLE
lineargauge-configuring-the-ranges - table columns are not in correct order, header for Default Value column not correct - bug

### ISSUE THREAD

**Issue by ghost** [Infragistics/convertwire#240]
The Comparative ranges configuration summary chart, section's table does not exhibit the correct column order; the header for the Default Values column appears as "2"

![image](https://cloud.githubusercontent.com/assets/14225200/14728314/7459bf9a-0801-11e6-9f85-c09f3bd7fd58.png)

**Comment by craigshoemaker** [comment]
This is a complex table (merged cells) and it will be picked up by the tables report.
