### ISSUE TITLE
datachart-multiple-series.adoc code samples missing.

### ISSUE THREAD

**Issue by agoldenbaum** [Infragistics/convertwire#243]
Code missing for Visual Basic and C# parts for Android-ex build flag related platforms under "Multiple Series from Mixed Groups of Series" part of topic. Does not render for any of the build-flags, it appears.

**Comment by ig-ealbert** [comment]
I think this is the same as #242 (and #202, #203).

```
ifdef::android-ex[]

*In Visual Basic:*

ifdef::xaml-xf-ex[]
```

Again, the code under 2 build flags won't appear in Livewire.

**Comment by craigshoemaker** [comment]
closing as it's a duplicate

**Comment by pamelabrasil** [comment]
The EN version of this topic is missing from the latest conversion

**Comment by ig-ealbert** [comment]
@pamelabrasil : This is one of the topics under the "topics-not-converted" folder (a3dde4c0...).  I don't know why that's the case, but it looks like @craigshoemaker is catching these instances.

**Comment by ig-ealbert** [comment]
@craigshoemaker, @pamelabrasil - My guess is that the table with empty `<tr>` elements is not parsing correctly and failing the conversion.  That's the only strange thing I've found in this topic.  I'm going to remove them (although I suspect they are separating sections) and see if that works.
http://help.infragistics.com/doc/WPF/2016.1/?page=DataChart_Multiple_Series.html

**Comment by craigshoemaker** [comment]
Unfortunately this still fails to convert. I will proceed with the overall conversion and will look at this again after to see if I can figure out why it's having an issue.
