### ISSUE TITLE
datachart-creating-chart-in-code-behind-winforms.adoc small conversion issues

### ISSUE THREAD

**Issue by agoldenbaum** [Infragistics/convertwire#245]
1. Extra underscore characters prior to DataChartName and after the word "control" in "Purpose section of topic.
2. Odd [_Ref396210216] exists after Creating Data Source link in "In this topic" section. Should exist in LiveWire "code," but not in document.
3. {DataChartLink} in "Application Requirements" seems slightly strange, but I'm not really sure where to find what exactly it's linked to. Does this {DataChartLink} correspond to Infragistics4 for WinForms build flag? If not, then this may be an issue...

Extra Notes:
Only build flag that exists here is Android-Ex. Should it just be WinForms, since this is a Win-Forms specific topic, and it differs a bit from the XAML related one?

**Comment by ig-ealbert** [comment]
@agoldenbaum - Good catch!  There was a very similar issue logged for another topic #200 (TFS 219328).
These are all issues except for 3 - it is a variable that corresponds to the current "AssemblyPlatform" variable in DocX.  It does become Infragistics4.  I guess @craigshoemaker renamed it which is ok.
I have logged TFS 219388 and will fix these issues in the source file.

**Comment by ig-ealbert** [comment]
Fixed.

**Comment by craigshoemaker** [comment]
Closing as @ig-ealbert reports as fixed.

**Comment by pamelabrasil** [comment]
removed build flags within topics as it was a winforms specific topic and didn't require build flags. Kept the project variables.
