### ISSUE TITLE
datachart-styling-the-chart-series.adoc font bolding issue

### ISSUE THREAD

**Issue by agoldenbaum** [Infragistics/convertwire#246]
In section "Overview" of "Style the Chart Series Drop Shadow Effect, "Applying drop-shadow..." parts of the Overview should be in a Bold font style.

**Comment by ig-ealbert** [comment]
I would disagree about this.  @craigshoemaker can confirm.  I think the styling you see here is just the header style for the online help.
http://help.infragistics.com/doc/wpf/2016.1/?page=DataChart_Styling_the_Chart_Series.html
It's not actually set to bold in the html.

```
<h4>Applying drop-shadow through the <span class="ig-code-in-text">Effect</span> property of the <span class="ig-code-in-text">Series</span> class</h4>
```

**Comment by craigshoemaker** [comment]
@ig-ealbert is correct. These elements are being correctly converted to `H4` elements (`====`) so any style concerns are a function of whatever stylesheet is applied to Livewire or the web app.
