### ISSUE TITLE
No code displayed under some headers

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#25]
datachart-category-stacked-100-line-series.ja-JP.adoc
No code is displayed under the "Visual Basic" and "C#" headers near the bottom.

**Comment by craigshoemaker** [comment]
You just need to add the correct build flag at the top and then they will appear.

**Comment by ig-ealbert** [comment]
The Java code is also build-flagged and yet it appears.

**Comment by ig-ealbert** [comment]
Another example is datachart-using-numeric-angle-axis.ja-JP.adoc.  All of the code snippets appear regardless of whether or not they are build-flagged in DocX.  This might be related to the many different build flag names.  Let me know if I should open a new issue about this.

**Comment by ig-ealbert** [comment]
datachart-configuring-itemlegend.ja-JP.adoc

**Comment by craigshoemaker** [comment]
I'll dig into this some more

**Comment by ig-ealbert** [comment]
This is better described in #36 and #38.
