### ISSUE TITLE
Bold list items are not bold

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#253]
This looks correct in AsciiDoc but doesn't render in Livewire correctly.  Where is it a bug?

```
* * WinButton*
* * WinCheckEditor*
* * WinCombo*
* *WinComboEditor* *
```

http://help.staging.infragistics.local/Doc/WinForms/2016.1/CLR4.0/?page=Coded_UI_Test_Extension_Overview.html

Observe the bolded list of controls.

Open the file coded-ui-test-extension-overview.adoc in Livewire.  This list is not bolded properly.  Only controls that have the extra `*` at the end (indicating a footnote) appear bolded.  The others have `*` in the preview.  Again, this looks correct in AsciiDoc.

**Comment by ig-ealbert** [comment]
Does this have to do with the space before the control name?

**Comment by craigshoemaker** [comment]
yep :)

**Comment by craigshoemaker** [comment]
Saving for later

```
value = value.replace(/\* \*( .+)\*/gi, (match, term) => {
    return match.replace(term, term.trim());
});
```
