### ISSUE TITLE
English and Japanese topics are not unmapped the same way

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#255]
Open xamarin-project-with-infragistics-controls.adoc in Livewire.
Compare it with the Japanese version in Livewire.

The English version is unmapped from the table.
The Japanese version is not unmapped, and around step 3 it breaks down and fails.  After that, code and list items are not rendered correctly.

**Comment by craigshoemaker** [comment]
I had an English-only selector :cry: 

it it how using the Japanese equivalent as well :smile: 

closed by 1f7bc243a81939a3cb4a8b6cf0b9a3c5b7b0f18f

**Comment by ig-ealbert** [comment]
Verified in final conversion.
