### ISSUE TITLE
The multiplication symbol should be escaped

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#259]
Open common control > ig-math-working-with-matrices.adoc in Livewire.

Observe the second link under the matrix operation types header.

The `*` symbol is missing because asciidoc interprets it as markup for bold syntax.

The symbol should be escaped either with `` or with \*.

**Comment by craigshoemaker** [comment]
closed by e186881ff53f293048be24058563328ebc36b5be

**Comment by ig-ealbert** [comment]
Verified - it uses `$$`.
