### ISSUE TITLE
Code is not parsed correctly inside tables

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#26]
Code is not parsed correctly inside tables.
datachart-visualizing-multi-dimensional-data-(olap-data)-(xamdatachart).ja-JP.adoc
Ex. [source, xaml]

**Comment by craigshoemaker** [comment]
Looks like source blocks are note supported inside tables. I will work around this by surrounding the code in [passthrough blocks](http://www.methods.co.nz/asciidoc/userguide.html#X76).

**Comment by craigshoemaker** [comment]
The [AsciiDoc guide on tables](http://www.methods.co.nz/asciidoc/newtables.html) may have some examples that could help in getting code to show up in tables.

I suspect topics like these will need some manual love to get them to display correctly.

**Comment by craigshoemaker** [comment]
Looks like the recent updates I did to the tables conversion has taken care of this issue automatically.
