### ISSUE TITLE
Headers with child build-flagged anchor tags are rendered differently between languages

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#261]
Open control-persistence-framework.adoc in Livewire.  Click on one of the build flags.

In Japanese, you’ll notice that the `==` (`<h2>`) syntax is not included in the pick statement.  The source content matches between English and Japanese, but the livewire preview and asciidoc are different.  Something you’re changing in English only?  This is actually the correct conversion based on the source file.

In English, the content is if-def’ed, but the headers are not (they are in the .xml file).  So you’ll notice that there will be a header (with a link that won’t work) and no description below it.  This is not converted correctly based on the source file, which is why I'm wondering if you're doing something different between languages.  Neither of the outcomes matches what is rendered in the online help.

![cpf](https://cloud.githubusercontent.com/assets/8162597/15898711/49ba3cc0-2d67-11e6-8867-61539184b1bf.png)

Here is the XML from the DocX content.  Theoretically the `<h1>` elements should be build-flagged instead of the `<a>` elements, but that would be a large change as this probably happens A LOT.

```
&lt;H1&gt;&lt;A href="ffd7c9ee-5103-4a99-9ce8-7ba27104a275" style="auto-update-caption: true" style="hs-build-flags: {A72AF817-CD06-4101-A8ED-A0E52FC4DD05},{673B143B-6568-4204-99C0-4548E4AFEF3C},34ADE70F-C190-412D-A2CE-25D1E1AE0FF8"&gt;Getting Started with Infragistics Control Persistence Framework&lt;/A&gt;&lt;/H1&gt;
&lt;P style="hs-build-flags: {A72AF817-CD06-4101-A8ED-A0E52FC4DD05},{673B143B-6568-4204-99C0-4548E4AFEF3C},34ADE70F-C190-412D-A2CE-25D1E1AE0FF8"&gt;In order to get you up and running as quickly as possible with the&amp;nbsp;Infragistics Control Persistence Framework, we've provided you with information on how to get started.&lt;/P&gt;
&lt;H1&gt;&lt;A href="Persistence_Getting_Started_with_IG_Control_Persistence_Framework.html" style="auto-update-caption: true" style="hs-build-flags: 27968E2C-EB4E-49F9-9A03-2FF58C6428F6"&gt;Persisting the Settings of an Object Using Infragistics Control Persistence Framework &lt;/A&gt;&lt;/H1&gt;
&lt;P style="hs-build-flags: 27968E2C-EB4E-49F9-9A03-2FF58C6428F6"&gt;In order to get you up and running as quickly as possible with the&amp;nbsp;Infragistics Control Persistence Framework, we've provided you with information on how to get started.&lt;/P&gt;

```

**Comment by craigshoemaker** [comment]
Okay there are a few issues going on here. Saving this regex here for now:

```
(=={1,}) pick:\[.+=\"
```

this will help move the title characters inside the pick macro.

**Comment by ig-ealbert** [comment]
Verified in final conversion.
