### ISSUE TITLE
datachart-creating-chart-in-code-behind - Build Flags displaying incorrectly

### ISSUE THREAD

**Issue by pamelabrasil** [Infragistics/convertwire#263]
This topic is build flagged for XAML and ANDROID only, however the WINFORMS build flag is displayed for the topic.

**Comment by ig-ealbert** [comment]
@pamelabrasil - That's because of the DROID_EX build flag.  All of the C# and VB code snippets are flagged as such.  This would be a content issue that you can fix in DocX.

**Comment by craigshoemaker** [comment]
closing per @ig-ealbert's comments to fix in DocX

**Comment by ig-ealbert** [comment]
@pamelabrasil - Could you please fix this in Document X if you think it should be fixed?  If the topic is build flagged for only XAML and Android, then the topic will not be shown in Windows Forms, so it won't matter that the code build flags include Windows Forms.

**Comment by pamelabrasil** [comment]
I updated the flags in the EN and JP version. removed droid_ex flag and replaced with XAML flag
