### ISSUE TITLE
xaml-xf-ex build flag is still used

### ISSUE THREAD

**Issue by pamelabrasil** [Infragistics/convertwire#264]
this build flag should be broken down in to SL, WPF, WINPHONE, WINRT

**Comment by HUSSAR-mtrela** [comment]
@craigshoemaker docx is using "xam-xf-ex" with out the L after "xam" and that could explain why this build flag is not broken down in to SL, WPF, WINPHONE, WINRT
In addition WIN-UNIVERSAL should be part of the "xaml-xf-ex"

**Comment by craigshoemaker** [comment]
`xam-xf-ex` is now being replaced with `wpf,win-universal`. closed by df77dae651491acdda617cea0d4a6b2d1807c0ea
