### ISSUE TITLE
[SL] A topic is not rendered correctly in "What’s New in 2014 Volume 2" topic

### ISSUE THREAD

**Issue by tachojelev** [Infragistics/convertwire#266]
**Steps to reproduce:**
1. Open silverlight.zip /whats-new-in-2014-volume-2.adoc
2. Navigate to "Infragistics Excel Engine" section

**Actual Result:**
The part above "Infragistics Excel Engine" is not rendered correctly. The reference "**[_Ref398210540]
<<,>>**" is visible.

**Expected Result:**
The part above "Infragistics Excel Engine" is rendered correctly. The reference "**[_Ref398210540]
<<,>>**" is not visible.

![issue](https://cloud.githubusercontent.com/assets/12784974/15958773/2a2b2992-2f00-11e6-98c0-7c66f59fb360.png)

**Comment by ig-ealbert** [comment]
@tachojelev - This is an issue with the DocX file.  The conversion is correct.  Here's the HTML:

```
<h4><a href="#_Ref398210540"></a></h4>

<p><a href="#"></a></p>

<div class="ig-block-title">
    <h2><a name="_Ref398210540"></a><i>Infragistics Excel Engine</i></h2>
</div>
```

I'll fix it in TFS when I figure out which anchor tag is correct.  But the `<<,>>` comes from that extra paragraph tag with the empty anchor, and the first line comes from the extra h4 tag with the anchor inside.

**Comment by ig-ealbert** [comment]
Fixed.  Removed the following markup:

```
<h4><a href="#_Ref398210540"></a></h4>

<p><a href="#"></a></p>
```

**Comment by craigshoemaker** [comment]
thanks @ig-ealbert!
