### ISSUE TITLE
Included topics are only in English

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#267]
This is copied from the Livewire issue: https://github.com/Infragistics/livewire/issues/70.

Open (WPF) xamdiagram-configuration-overview.ja-JP.adoc in Livewire.

Observe the parts underneath "XamDiagram Configuration Summary" and "XamDiagram Configuration Summary Chart".

These parts of the topics are in English, because they are referencing another topic a la:
`include::xamdiagram-configuration-summary.adoc[]`
`include::xamdiagram-configuration-summary-chart.adoc[]`

They should be in Japanese.  Is there a way to detect the language of the file that's being converted and add ".ja-JP.adoc" to the file names of included files instead?

If necessary, once we have the final conversion, I can do a search and add .ja-JP to all of the include:: lines.

https://github.com/Infragistics/convertwire/blob/master/modules/html2AsciiDoc/converters-ig-structure.js

**Comment by craigshoemaker** [comment]
closed by abdaa0531c08046454ab1cf41f7e8f530ff43f48

**Comment by ig-ealbert** [comment]
@craigshoemaker This works mostly... it doesn't translate the title / header item of the included topic.  How do you suggest I fix this manually, if that's what needs to be done?

**Comment by ig-ealbert** [comment]
@craigshoemaker : Figured out the problem. There shouldn't be a title in these snippet topics.  I'm not sure if that's going to mess up anything by removing them?  Please provide guidance on how to proceed.  I could remove the titles from the EN and JA topics, but I don't want to break anything.  Also, related to our training discussion, how do I go about making this change?  Branch then commit and push?  Submit a pull request from a branch?

**Comment by craigshoemaker** [comment]
you can just rip out those offending titles and then commit your changes to the repository

**Comment by ig-ealbert** [comment]
http://tfs.infragistics.local:8080/tfs/Engineering/IgInternalApplicationsGit/_git/wpf-docs-en/commit/48d89c01b6480a4809c750b325f8b145cc0b0ee2
http://tfs.infragistics.local:8080/tfs/Engineering/IgInternalApplicationsGit/_git/wpf-docs-ja/commit/07071592898ad6ff039b99d014c7fc1ff2eb253f
Fixed.
