### ISSUE TITLE
Some commits don't work with Node 4.5.0

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#275]
Could you please revise the following functionality so that it works with Node 4.5.0?  This seems to be related to the "let" new functionality in Javascript.
https://github.com/Infragistics/convertwire/commit/1d84358199b962b2b08f3cad4822b087789debf0
https://github.com/Infragistics/convertwire/commit/26caa2fcb0497e0d1b86b0bd087f997cf555a0c4

**Comment by craigshoemaker** [comment]
closed by e023891249e34328068793d0d9b58f1e3d4d4802
