### ISSUE TITLE
datachart-axis-tick-marks.adoc

### ISSUE THREAD

**Issue by pamelabrasil** [Infragistics/convertwire#30]
Required Background is blank
Missing build flags on last row of the Property Settings table
Related Content is blank

**Comment by craigshoemaker** [comment]
closed by ea18ac3e6bf6d513f6e1ebeef2f7aa887e2fca38

**Comment by craigshoemaker** [comment]
The missing content is closed by ea18ac3e6bf6d513f6e1ebeef2f7aa887e2fca38

But I still need to look into build flagging rows of tables.

**Comment by craigshoemaker** [comment]
implemented build-flagged table rows. closed by 01c63ae2b55470c962104f97e97238ca76c18e73
