### ISSUE TITLE
datachart-categoryhighlightlayer.adoc

### ISSUE THREAD

**Issue by pamelabrasil** [Infragistics/convertwire#34]
Required background information does not appear in a table
In this Topic information is missing
First sentence of Category highlight layer overview text appears as- xamDataC__hart control
Samples information is missing

**Comment by ig-ealbert** [comment]
The first two might be related, maybe some bad HTML?
The first sentence issue is a content issue.  It should be logged in TFS if Craig decides that a regex cleanup is not going to work.  See issue #28 for his comments about that.
The samples information is a duplicate of #37.

**Comment by craigshoemaker** [comment]
All the items noted here are fixed except for the underscore in xamDataC__hart. This should be fixed in the source document manually. I have added it to the fix list.

**Comment by ig-ealbert** [comment]
Looks like this was also fixed in TFS 210073.
