### ISSUE TITLE
Topic names are included in the link text

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#35]
Other topic names are included in the link text for related topics.

datachart-category-stacked-spline-area-series.ja-JP.adoc

Scroll to the bottom.
積層エリア シリーズdatachart-category-column-series.html

積層 100-スプライン エリア シリーズdatachart-category-stacked-bar-series.html

**Comment by ig-ealbert** [comment]
This seems to be a content problem with the Document X file. Probably happens in English too.  There are blank anchor tags at the end of these lines.  Should I submit this in TFS as a content issue?

**Comment by pamelabrasil** [comment]
I don't see any blank anchor tags at the end of these lines in DocX

<h1 id="RelatedTopics" name="RelatedTopics">Related Topics</h1>

<p><a href="DataChart_Axes.html">Axes</a></p>

<p><a href="DataChart_Category_Series_Overview.html">Category Series</a></p>

<p><a href="DataChart_Category_Area_Series.html">Area Series</a></p>

<p><a href="DataChart_Series_Requirements.html">Series Requirements</a></p>

<p data-build-flags="XAM_XF_EX,WINFORMS,ANDROID"><a href="DataChart_Category_Stacked_Spline_Series.html">Stacked Spline Series</a></p>

<p data-build-flags="XAM_XF_EX,WINFORMS,ANDROID"><a href="DataChart_Category_Stacked_100_Spline_Series.html">Stacked 100-Spline Series</a></p>

**Comment by pamelabrasil** [comment]
hmmm, I wanted that to appear in code..

**Comment by pamelabrasil** [comment]
Ok, I fixed that issue in DocX and checked it, so the next batch shouldnt have this issue. Liz, you can close this.

**Comment by ig-ealbert** [comment]
Fixed in 15.2 (by me) and 16.1 (by Pam) in TFS.
