### ISSUE TITLE
Code is not getting build flagged properly

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#36]
Code snippets that should be build flagged are not properly build flagged in asciidoc.

datachart-docking-legends.ja-JP.adoc

There are 3 XAML code snippets that should be build-flagged for SL/WPF, WinRT, and Windows Phone. However, none of them are build flagged so they all appear.
$/NetAdvantage/DEV/Common/2015.2/PG/DataChart/topicdata/fb5bd3f3...

Even if we don't support Windows Phone and WinRT anymore, we have to make sure that these code blocks are build flagged so they do not all appear.

**Comment by ig-ealbert** [comment]
resources-numeric-data-sample-1.ja-JP.adoc
Same issue - multiple code snippets are not being build-flagged so they are all showing at once.

**Comment by ig-ealbert** [comment]
datachart-using-category-angle-axis.ja-JP.adoc

**Comment by ig-ealbert** [comment]
resources-sample-energy-data.ja-JP.adoc

**Comment by ig-ealbert** [comment]
datachart-axis-orientation.ja-JP.adoc

**Comment by craigshoemaker** [comment]
Okay - this is taken care of now except for the fact that `resources-sample-energy-data.ja-JP.adoc` isn't build flagged in the source document so there is nothing to pick up during conversion.
