### ISSUE TITLE
Samples table is missing from the asciidoc file

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#37]
The samples table is missing except for the header.

datachart-crosshairlayer.ja-JP.adoc

Scroll to the bottom.  There is just "Samples" with no table.  Check the AsciiDoc - it's not there either.

Original file for reference:
$/NetAdvantage/DEV/Common/2016.1/PG/DataChart/topicdata/d20ed73f

**Comment by ig-ealbert** [comment]
datachart-commonproperties.ja-JP.adoc

**Comment by ig-ealbert** [comment]
datachart-categoryhighlightlayer.ja-JP.adoc

**Comment by craigshoemaker** [comment]
Okay - I think I've got it this time. I rewrote the module that deals with the IM tables so this is closed by 4eb0ed0380314deb22d9224e8ac19119216bc941
