### ISSUE TITLE
Note text is in English

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#52]
Open any file with a note in it in Livewire.
wintoolbarsmanager-navigation-toolbar-show-the-navigation-toolbar.ja-JP.adoc

Observe the note.
The header "Note" is in English.
This should be in Japanese.  It should appear that way in the build, at the very least.

**Comment by craigshoemaker** [comment]
closed by 95e95f099e5a73f87e680220f4b2a69f17ae5092
