### ISSUE TITLE
Old versions of API links are not removed

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#55]
Open any topic that has old API links (for CLR2.0, 3.5, and 4.0).  Ex.
wingauge-apply-the-image-brush-element-at-design-time.adoc

Observe the API links (steps 3 - 5).

These links are listed 3 times, once for each CLR version.

Only the CLR4.0 (or latest) version should be referenced.  I don't think the plan to retire CLR4.0 will affect this, as 4.6 is still part of 4.0 APIs, right?  This is technically a content issue.  Let me know if we need to do a massive find across all product documents to fix this (can't automatically replace it).  That may take a long time so it would be good to fix this through convertwire if possible.

**Comment by craigshoemaker** [comment]
I posted a new build of the help yesterday. Please take a look at the latest version of this topic and let me know if this is still an issue.

**Comment by ig-ealbert** [comment]
Seems to be an issue in the Japanese topic only.  Looks like these CLR2 and CLR35 links were removed in English but not in Japanese.  I expect this to be a widespread issue, so I logged TFS task 211571 for me to fix these topics.

**Comment by ig-ealbert** [comment]
It seems that some formerly shared topics between win and web were duplicated and added to each project.  They have different build-flags for CLR versions and also web and win.  The web build flags don't need to be in the win topics and vice versa.  I'm adding the information to the task as I go.
