### ISSUE TITLE
Internal links do not point to anywhere in the topic

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#56]
Open winganttviewprintdocument-print-preview-with-winganttviewprintdocument.adoc.

Observe the links to other sections of the topic (ex. <<_Ref317523170, [text]>>).  Try to find the matching parts of the asciidoc file.  They should be labeled with the same id, right?

These internal link ids do not exist.  Meaning, if the topic is converted to HTML and the link is clicked, it won't go anywhere.  Is that correct?  Is this somehow generated when the topic is converted to HTML?

This is not specific to this topic - it will be a widespread issue as many topics use internal reference numbers like this.

**Comment by craigshoemaker** [comment]
This is actually an issue with the topic in the source DocumentX content. I verified that the unit tests for creating named anchors are passing and verified that named anchors are converting correctly in other topics.

I am closing this issue, but you should create an issue in TFS to have the source document fixed.

**Comment by ig-ealbert** [comment]
```
&lt;UL&gt;
&lt;LI&gt;&lt;A href="#_Ref317523170"&gt;Using Print Preview with the WinGanttView Control&lt;/A&gt; 
&lt;LI style="LIST-STYLE-TYPE: none; DISPLAY: inline"&gt;
&lt;UL&gt;
&lt;LI&gt;&lt;A href="#_Ref317523196"&gt;Introduction&lt;/A&gt; 
&lt;LI&gt;&lt;A href="#_Ref317523203"&gt;Preview&lt;/A&gt; 
&lt;LI&gt;&lt;A href="#_Ref317523211"&gt;Requirements&lt;/A&gt; 
&lt;LI&gt;&lt;A href="#_Ref317523217"&gt;Steps&lt;/A&gt; &lt;/LI&gt;&lt;/UL&gt;
&lt;LI&gt;&lt;A href="#_Ref317523239"&gt;Related Content&lt;/A&gt; &lt;/LI&gt;&lt;/UL&gt;
```

There are sections of the topic like this:

```
&lt;DIV class=ig-block-title&gt;
&lt;H2&gt;&lt;A name=_Ref317523170&gt;&lt;/A&gt;Using Print Preview with the WinGanttView Control&lt;/H2&gt;&lt;/DIV&gt;
```

There _are_ sections with matching IDs (`_Ref317523170`), so the lack of matching target anchor tags is probably related to convertwire.

You had previously mentioned removing blank `<a>` tags, and I tried to point out that this could cause issues with target anchor tags.  Is this related?

**Comment by craigshoemaker** [comment]
still an issue per @ig-ealbert

**Comment by craigshoemaker** [comment]
The fix for this was to make the rule looking for these a bit more flexible. Before I was only detecting anchors with no text and an `id` value, but as this example demonstrates it needs to look for the `name` attribute as well.
