### ISSUE TITLE
Topic is mostly empty

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#58]
Open wingauge-back-anchor-extent-pane.adoc.

The topic is mostly empty in the Livewire preview.  This is probably due to the lack of headers in the table that is used for formatting.

If you need me to change it in TFS, I can log a bug for it.  It would just be nice to make sure that we catch all of these issues and can handle them without manually editing the topics.  Otherwise, could you suggest a search pattern?  Again, this would be a long manual task to fix all of these.

**Comment by craigshoemaker** [comment]
This is displaying just fine for me and it probably due to some of the recent changes I made to how tables are parsed. I'll call this one closed for now.

**Comment by ig-ealbert** [comment]
Verified as fixed.
