### ISSUE TITLE
Nested bold and italic styling don't preview correctly

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#61]
Open webhierarchicaldatagrid-configuring-multi-column-footers.adoc in Livewire.

Observe step 4.

ColSpan is marked with `*` in the preview window.

The AsciiDoc seems right, but it doesn't preview properly.

```
|フッターを _ProductName_ および _UnitPrice_ 列に追加します 
*1.フッターを* _ProductName_ *列に追加し、*_ColSpan_ *を 2 に設定します。* 
```

The .xml content is very messy but aside from that, it's "grammatically" correct and shouldn't render the `*`s.

**Comment by craigshoemaker** [comment]
This one is also closed by 11f6aa31520d4c725d1cff3bcf37ceb3e3e35d91 as I added extra whitespace to italics as well as bold
