### ISSUE TITLE
Nested block quotes are not handled properly

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#64]
This might also be a content issue, but I don't know the expected result.  You might want to consult Pam or someone on the ASP.NET team, as the current nested structure doesn't really make sense to me.

Open webscheduleinfo-csom-overview.adoc in Livewire.  (Note the content is different in Japanese and  I don't know which is correct.)

The online help has nested block quotes.  The .adoc file does not.
http://help.infragistics.com/doc/ASPNET/2015.2/?page=WebScheduleInfo_CSOM.html

Again, if this is a content issue, it will be very difficult to fix outside of this one topic.  I feel like for hierarchical lists, we should be using list items instead of block quotes.  Might be best to ask someone who knows about the WebSchedule if this nested structure even makes sense.

**Comment by craigshoemaker** [comment]
Nested `blockquote` elements... that is a first for me :)

Yes, hierarchical data should be in a list or something... anything, really, except nested blockquotes :frowning: 

Yeah this is really bad markup, but I doubt it will show up very often. I have added this to the post-conversion report so these topics can be fixed before or after the final conversion.

I am calling this one closed by 50118329f080afdecee5c03c6b3b7bf5da422167
