### ISSUE TITLE
Paragraph content in certain tables is not shown as paragraphs

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#65]
Open webgauge-annotations-bounds-pane.adoc in Livewire.
The text all runs together - it is not separated by paragraphs as it is in the HTML.  This might be because there are no table headers?  I had submitted about certain topics not rendering when this occurs, but now the paragraph tags are being ignored.  Is that because table headers cannot contain paragraph tags?

**Comment by ig-ealbert** [comment]
webgauge-value-and-units.adoc

**Comment by ig-ealbert** [comment]
I think this is the same issue, not sure.
view-source:http://help.infragistics.com/Help/Doc/ASPNET/2015.2/CLR4.0/html/Known_Issues_Known_Issues_and_Breaking_Changes_Revision_History.html
known-issues-known-issues-and-breaking-changes-revision-history.adoc
The code snippet under Example: Accessing the clipboard using a Flash object doesn't respect the `<p>` tags so it is unreadable.

**Comment by craigshoemaker** [comment]
Using tables for layout is really problematic to convert. I added this to the reporting module to have Product Teams look at manually.
