### ISSUE TITLE
Table with empty first TH is not parsed correctly

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#71]
Go here:
http://help.infragistics.com/doc/ASPNET/2015.2/?page=Known_Issues_Known_Issues_and_Breaking_Changes_Revision_History.html
Compare with known-issues-known-issues-and-breaking-changes-revision-history.adoc in Livewire.
Scroll down to "Create a Templated Cell on the Client" - "Workaround".
The last column shown in the table in Livewire should be the first column, with an empty header.

**Comment by ig-ealbert** [comment]
Also happens in WPF xamdiagram-configuring-the-shape-of-diagram-nodes-overview.adoc.
http://help.infragistics.com/doc/WPF/2015.2/?page=xamDiagram_Configuring_the_Shape_of_Diagram_Nodes_Overview.html

**Comment by ig-ealbert** [comment]
Tables with empty cells don't seem to be parsing correctly.
xamdiagram-user-interactions-configuration-summary-chart.adoc (empty cell in first data row).
http://help.infragistics.com/doc/WPF/2015.2/?page=xamDiagram_User_Interactions_Configuration_Overview.html

**Comment by ig-ealbert** [comment]
Found this in the table with MANY columns in igbarcodeview-barcode-types.adoc.  I think it's the same issue as the first TH is empty.

**Comment by craigshoemaker** [comment]
Support for empty THs is now implemented

**Comment by ig-ealbert** [comment]
@craigshoemaker : Did you mean "now" or "not"?  If you did indeed mean "not", how can we handle this?

**Comment by craigshoemaker** [comment]
@ig-ealbert :smile: I meant "now"

**Comment by craigshoemaker** [comment]
still an issue per @ig-ealbert

**Comment by craigshoemaker** [comment]
@ig-ealbert

I have checked each document in EN and JP and all tables in theses topics are converted correctly:
- `xamdiagram-configuring-the-shape-of-diagram-nodes-overview.adoc` *
- `xamdiagram-user-interactions-configuration-summary-chart.adoc`

\* except for the table with merged columns/rows which are picked up in the conversion reports

The table in `igbarcodeview-barcode-types.adoc` is a bit of a special case. This table is comprised of a number of special characters that are styled with the wingdings font. This approach won't work in AsciiDoc topics. I have added wingdings to the reporting module so any topics that use them will be flagged for manual processing.

Beyond that all tests are passing and I belive this one is done.

**Comment by craigshoemaker** [comment]
commit that adds wingings to reporter fce41dc52f6a88cf322223f0a8d3139f3a3aac33

**Comment by ig-ealbert** [comment]
Did you check the first ASP.NET topic I listed?  It's still an issue.

**Comment by craigshoemaker** [comment]
@ig-ealbert ah yes, that was the one I started with and just forgot to include it in my last summary. This is how the _Workarounds_ table in `known-issues-known-issues-and-breaking-changes-revision-history.adoc` is rendering now:

![image](https://cloud.githubusercontent.com/assets/127797/12990806/1cfb6252-d0c1-11e5-9b93-7d340690e279.png)
