### ISSUE TITLE
API links are not previewed correctly

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#76]
Open sl-xamtree-setting-expanded-and-collapsed-icons.adoc in Livewire.
Compare with the online version.
http://help.infragistics.com/doc/Silverlight?page=SL_xamTree_Setting_Expanded_and_Collapsed_Icons.html

In Livewire, the API links do not show up as links.  I feel like we had discussed this as expected a while ago, but I don't remember seeing it when I was reviewing Windows Forms or ASP.NET.

**Comment by craigshoemaker** [comment]
This is remedied in the latest build although I don't have a specific build to point this issue to.

**Comment by craigshoemaker** [comment]
still an issue per @ig-ealbert

**Comment by craigshoemaker** [comment]
@ig-ealbert this one also seems to be to be resolved, but you let me know. I just re-converted the topic and here's what I see:

![image](https://cloud.githubusercontent.com/assets/127797/12957016/a53e2998-cfdf-11e5-96cd-54e710dfc001.png)

**Comment by ig-ealbert** [comment]
I don't mean the related topic links.  I meant the links in the first paragraph.  I don't know why, but this seems to only be an issue in Japanese now.  Here is what I see:
![image](https://cloud.githubusercontent.com/assets/8162597/12959561/f5892630-d004-11e5-8782-01c4adb1a9c0.png)
I compared the link syntax between English and Japanese and it seems to be the same.  Could it be caused by a lack of a space before the first link?

**Comment by craigshoemaker** [comment]
I see what you're saying now. The culprit here is an extra space inside the link for the JP topic. Not sure how it got there, but I added a rule to clean that up as well.
