### ISSUE TITLE
Line break is not correctly rendered

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#78]
Open virtual-collection-using-virtual-collection.adoc in Livewire.
Compare with the online help:
http://help.infragistics.com/doc/Silverlight?page=Virtual_Collection_Using_Virtual_Collection.html
There are `<br />` elements in the HTML but the line breaks are not shown in the preview.  There might need to be 2 line returns in AsciiDoc?

**Comment by ig-ealbert** [comment]
Also happens with related topics in whats-new-2009-volume-1.adoc.

**Comment by craigshoemaker** [comment]
Closed by 1ecc099c773ddf1554a5e014ed3f4ff6e4726ae2
