### ISSUE TITLE
Related topics content is missing

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#79]
Open SL whats-new-in-2009-volume-1.adoc in Livewire.
Observe the related topics section under XamWebChart.  This happens for multiple other control sections in this topic.
Compare with the online help:
http://help.infragistics.com/doc/Silverlight?page=Whats_New_in_2009_Volume_1.html
It is empty.  There are titles of topics (not linked because the control was retired), but these titles do not appear in the .adoc file.  You might want to discuss with Pam how to handle these, as it is correct that they are not linked.  I don't know if we should just show the text (that would be my guess) or if we should change the content to remove these?  It will be very difficult to do some find operation to get unlinked related topics.

**Comment by craigshoemaker** [comment]
The issue here is that the `BR`s are not being parsed correctly (which is remedied by 1ecc099c773ddf1554a5e014ed3f4ff6e4726ae2).

**Comment by craigshoemaker** [comment]
still an issue per @ig-ealbert

**Comment by craigshoemaker** [comment]
@ig-ealbert here’s what I am seeing in the topic:

![image](https://cloud.githubusercontent.com/assets/127797/12956752/5fef5bec-cfde-11e5-86df-caf24541e268.png)

This issue appears to me to be resolved, but perhaps I am missing something?

**Comment by ig-ealbert** [comment]
This still happens in the .ja-JP.adoc file, but it's a content issue.  I will log a bug in TFS to fix that.
