### ISSUE TITLE
Merged cells do not appear correctly in the table

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#80]
Open whats-new-in-2013-volume-2.adoc (Silverlight) in Livewire.
Compare with the online help.
http://help.infragistics.com/doc/Silverlight?page=Whats_New_in_2013_Volume_2.html
The table with the list of new features is wrong.  The "xamDataChart" cell is supposed to span multiple rows, but it does not.  This shifts the content of the other cells into the wrong columns.  It also loses the last 2 TDs.
Same thing happens in whats-new-in-2013-volume-1.adoc.
http://help.infragistics.com/doc/Silverlight?page=Whats_New_in_2013_Volume_1.html

**Comment by ig-ealbert** [comment]
Also happens in WPF xamdiagram-configuring-the-shape-of-diagram-nodes-overview.adoc.
http://help.infragistics.com/doc/WPF/2015.2/?page=xamDiagram_Configuring_the_Shape_of_Diagram_Nodes_Overview.html

**Comment by craigshoemaker** [comment]
Any table with merged cells needs to be manually processed and will be picked up by the tables report.
