### ISSUE TITLE
{WPFSpecific} appears at the top of the topic

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#83]
Open xamdatapresenter-printing.adoc in Livewire.
{WPFSpecific} appears at the top of the .adoc file and the preview.
I don't know if this is expected?  Why is metadata about the topic's target product shown in the content?

**Comment by craigshoemaker** [comment]
This is also a build variable that needs to be resolved before publishing. Closing this issue as the topic is parsed correctly.
