### ISSUE TITLE
{Warning} should be ignored?

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#84]
The xamRibbon (WPF) topics have some {Warning} label at the top.  I vaguely remember that this was because Microsoft was SUPER STRICT about the usage of its ribbon, and there was like a 70+ page document about all of the rules you had to follow.  I think they since eased up on this, but I'm not sure.  Well, it would explain why that warning doesn't appear in our help anymore.
Ex.
Open xamribbon-label.adoc in Livewire.
Compare with the online help.
http://help.infragistics.com/doc/WPF/2015.2/?page=xamRibbon_Label.html
In the online help, no warning appears.
If you can confirm with Pam or Radko or whoever would know, then this should probably be ignored and not included in the asciidoc?

**Comment by craigshoemaker** [comment]
`{Warning}` is a build variable. It looks like the help is being built without a value for that variable. Since this is parsed correctly, I'll close this issue.
