### ISSUE TITLE
Content is not rendered in Livewire preview for chart

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#86]
Open chart-column-chart-2d.adoc in Livewire.
The content is not rendered after the image, even though there is content in the .adoc file.
http://help.infragistics.com/doc/WinForms/2015.2/?page=Chart_About_2D_Spline_Charts.html

**Comment by ig-ealbert** [comment]
Similarly, the first image and paragraph are missing from chart-about-polar-charts.adoc.

**Comment by ig-ealbert** [comment]
The first 2 paragraphs are missing from chart-apply-a-hatch-style-to-a-primitive.adoc.

**Comment by craigshoemaker** [comment]
These topics are rendering correctly now. (The ultimate fix may have been remedied in a previous commit.) The image not showing up in `chart-column-chart-2d.adoc` because the image is not longer in the original document.
