### ISSUE TITLE
Code section inside a blockquote is not being rendered as code

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#87]
Open chart-working-with-3d-bar-chart-data.adoc ("chart", from WebAndWin) in Livewire.
Scroll down to the code above the last table.
It is not rendered as code, even though it is in `<code>` tags.  This is probably because it's in a blockquote.
The code should be rendered as such even inside a blockquote.

**Comment by ig-ealbert** [comment]
Also happens in chart-working-with-scatter-chart-data.adoc.

**Comment by craigshoemaker** [comment]
Since `code` or `pre` elements should not be inside `blockquote` elements, I have added this to the report that is run post-conversion.

**Comment by craigshoemaker** [comment]
closed by 6a121b2d9ac1b38340b9e4f55b220e800902efd2
