### ISSUE TITLE
Headers and paragraphs are not rendered properly in table

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#88]
Open documentengine-flow.adoc in Livewire.
Note that the headers and paragraphs are not rendered as such in the table at the top.  This might be because the table header cannot contain these elements?  If so, could it be created as a headerless table?  It would be a lot of manual work, unless you can think of a way to detect this, to edit all topics where there are headerless tables.

**Comment by craigshoemaker** [comment]
This is closed by 69fde618433198a397c94adb9df9dbf6c34a5c4b
