### ISSUE TITLE
Inline `<code>` blocks are not rendered properly

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#89]
Open documentengine-flow.adoc in Livewire.
Observe the 3rd step, above the lorem ipsum text.
"string1" should be in code.  However, "variable:" should not be.  It is not wrapped in code tags.  Inline code should be more like an applied background and foreground color and font.

**Comment by craigshoemaker** [comment]
Here's one of the places where inconsistencies in the source topics are causing issues for the converted topics. To have in-line code the source should be using a `SPAN` element with the CSS class of `code-in-text` applied. I am going to close this issue as the topic is being parsed correctly, but I'll add it to the manual review list (as it has many other issues that require attention as well.)

**Comment by ig-ealbert** [comment]
@craigshoemaker : The original topic was created long before the CSS classes for code-in-text.

```
&lt;CODE class=code&gt;string1&lt;/CODE&gt;
```

I hope this isn't a widespread issue but we may have to review A LOT of old topics if `<CODE>` isn't treated correctly inline.  Is there any way to have a report on this?  I think it would be easier to fix it in AsciiDoc than in Document X.
