### ISSUE TITLE
Layout element comparison table is not rendered properly

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#90]
Open documentengine-layout-element-comparison-table.adoc in Livewire.
Observe the table.
There is one column.
I have no idea where "11" came from.
There should be many columns.
Compare with the online help:
http://help.infragistics.com/doc/WinForms/2015.2/?page=DocumentEngine_Layout_Element_Comparison_Table.html

**Comment by craigshoemaker** [comment]
The 11 came from the converter trying to make sense of merged cells and not being able to do it ;). Closing this issue as this topic will bubble up in the merged-cell table reports.
