### ISSUE TITLE
Much of the topic is not rendered in the preview

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#93]
Open documentengine-canvas.adoc in Livewire.
Observe the preview.
It starts with a broken table.
It should start with, and display fully, the content in the .adoc file.
Compare with the online help:
http://help.infragistics.com/doc/WinForms/2015.2/?page=DocumentEngine_Canvas.html

**Comment by craigshoemaker** [comment]
Tables used for layout just don't convert :frowning:. Adding to manual fix list.

**Comment by craigshoemaker** [comment]
I thought of an automated way to deal with this over the weekend. I am optimistic it will work

**Comment by ig-ealbert** [comment]
@craigshoemaker : Is there anything specific here to fix in Document X?  Or do the product teams have to rewrite all of these old Document Engine topics?  Or is this fixed already?
