### ISSUE TITLE
Extra `*` appears after header

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#95]
Open excelengine-accessing-cells-and-cell-regions-by-name.adoc in Livewire.
Scroll down about halfway to the "Naming cells and regions in code" header.
There is an extra `*` after the header.  This might be because there is a nested internal anchor tag inside the bold tags.

```
<h4><a name="_Naming_cells_and_1"></a><b><a id="OLE_LINK59" name="OLE_LINK59"></a>Naming cells and regions in code</b></h4>
```

**Comment by craigshoemaker** [comment]
This is not an issue in the latest build.
