### ISSUE TITLE
Header is repeated for each link

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#96]
Open excelengine-filtering-tables.adoc in Livewire.
Observe the section under "Purpose".
"In this topic" is repeated for each link.
It should not be repeated.
Compare with the online help:
http://help.infragistics.com/doc/WinForms/2015.2/?page=ExcelEngine_Filtering_Tables.html
Also happens for excelengine-preserving-table-formatting-when-loading-excel-files.adoc.
http://help.infragistics.com/doc/WinForms/2015.2/?page=ExcelEngine_Preserving_Table_Formatting_When_Loading_Excel_Files.html

**Comment by ig-ealbert** [comment]
xampivotgrid-printing.adoc (CommonControls) also has this issue for the overview steps.

**Comment by josheela** [comment]
similar issue : 

doc : winnavigationbar.adoc
online link: http://help.infragistics.com/doc/WinForms/2015.2/?page=WinNavigationBar.html

Header links 
1. Understanding WinNavigationBar
2.  Using WinNavigationBar
3. API Overview
   are being repeated as heading and then the link.
