### ISSUE TITLE
Link is not correctly ifdef'ed

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#97]
Open designersguide-styling-points.adoc in Livewire.
Observe the preview.
Only one link shows up as a "pick".  The others are all ifdef'ed.  Is this intentional?  If so, why is this not ifdef'ed as SL only?

**Comment by craigshoemaker** [comment]
This is due to some _interesting_ source markup. This topic has some strangely nested build flags. In the end once Livewire supports the `pick:` syntax it won't look so odd, but it should be fixed. Adding to manual list.

**Comment by ig-ealbert** [comment]
TFS 219334 - Fixed (in English only - it was fine in Japanese at least in the XML file).
