### ISSUE TITLE
Class "ig-level-1" is still not used

### ISSUE THREAD

**Issue by ig-ealbert** [Infragistics/convertwire#99]
#53 doesn't seem to be fixed if the latest zip files contain the fix.

Ex.
http://help.infragistics.com/doc/Silverlight/2015.2/?page=Version-Free_Assemblies.html

Open version-free-assemblies.adoc in Livewire.  The list under "In this topic" is still not a list.

**Comment by craigshoemaker** [comment]
Here the conversion supported needed to include `ig-level-1` through `ig-level-3`
